### ISSUE TITLE
create time plots after map does not working

### ISSUE THREAD

**Issue by idoyehe** [pywren/pywren-ibm-cloud#113]
Hi @JosepSampe
I remember that I used the method "create_timeline_plots" right after getting result with path and job name and it used to create plots about the invocations in my local filesystem but it seems that something goes wrong with that because it doesn't work anymore... 
That plot are not created and I debug the method and it seems self.future is an empty list...

Can you please check that, I guess this is not big problem because it used to work.

Thanks,
Ido

**Comment by JosepSampe** [comment]
@idoyehe Yep, I already realized that. It is fixed with #112

**Comment by idoyehe** [comment]
Thnaks, I found the problem in wren.py line 314 set self.future to an empty list...
