### ISSUE TITLE
Low bandwidth accessing to COS from some activations

### ISSUE THREAD

**Issue by JosepSampe** [pywren/pywren-ibm-cloud#123]
I'm running an experiment that consists of 400 actions (in parallel) accessing to COS to read 250MB each one. 

The problem is that, each time I run the experiment, there are always between 1 and 4 actions that, for some reason, get very low bandwidth. For example:
![bad_cos_bw](https://user-images.githubusercontent.com/10448186/56064813-66dea400-5d73-11e9-8ca2-ee4455c3c1ae.png)
As shown in the plot, in that experiment there were 3 actions that took more than 330 seconds to read its 250MB, while the rest of the actions took 10 seconds.

I'm already investigating what causes the issue.

**Comment by gilv** [comment]
@JosepSampe thanks...trying also to figure out what might be wrong

**Comment by JosepSampe** [comment]
@gilv My suspicious is that it is something related to CF cluster and not to PyWren itself. For the moment what I did is to log all the IPs where the functions are executed. And then log the IPs where those functions that slow-read from COS are executed . 

This is an example of the distribution:
`{'192.168.0.10': 5, '192.168.0.11': 44, '192.168.0.12': 43, '192.168.0.13': 55, '192.168.0.14': 53, '192.168.0.15': 34, '192.168.0.16': 38, '192.168.0.17': 34, '192.168.0.18': 33, '192.168.0.19': 5, '192.168.0.2': 5, '192.168.0.20': 2, '192.168.0.21': 2, '192.168.0.22': 2, '192.168.0.23': 3, '192.168.0.24': 1, '192.168.0.26': 1, '192.168.0.27': 2, '192.168.0.28': 1, '192.168.0.4': 6, '192.168.0.41': 1, '192.168.0.44': 1, '192.168.0.45': 1, '192.168.0.46': 1, '192.168.0.5': 6, '192.168.0.6': 5, '192.168.0.7': 4, '192.168.0.8': 5, '192.168.0.9': 7}`

And seems that the functions that go slow always come from the same nodes, these nodes are IPs from 192.168.0.20 to 192.168.0.27

Is you see the distribution, range 192.168.0.10 to 192.168.0.19 can execute tens of functions: In contrast, ips from 192.168.0.20 to 192.168.0.27 can only execute few functions... This means that the first ones are new nodes and the second ones are old nodes? I'm in us-east.

**Comment by JosepSampe** [comment]
@gilv Seems that for some reason, those nodes (ips from 192.168.0.20 to 27) sometimes have problems accessing COS though the public endpoint. By using private endpoint the issue is completely solved 100% of times. 

Fixed in #126
