### ISSUE TITLE
"Verify" section in readme is not clear enough

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#124]
It seems that running python3 test/testpywren.py init requires to clone the project. However all previous steps explains how to use "pip install".

We need to adapt readme with explanation how to run tests if PyWren-IBM was installed with pip and also installed with clone?

**Comment by omerb01** [comment]
@gilv Currently the test file is an external script which stored in this repository,
maybe it will be better to make a dedicated PyWren's code for tests.

for example:
```python
import pywren_ibm_cloud as pywren
pywren.test()
```
How it sounds?

**Comment by gilv** [comment]
@omerb01 can we make both?

**Comment by omerb01** [comment]
@gilv #125
