### ISSUE TITLE
Verify Docker images in runtime folder

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#127]
There were many recent improvements in runtime deployments.
Would be good to verify Docker images in the runtime folder are up to date.
For example is this remains correct

        FROM python:3.6-slim-jessie, 
etc.

**Comment by gilv** [comment]
@JosepSampe can you please see it? thanks

**Comment by JosepSampe** [comment]
@gilv Yep, images are correct and aligned with the official one, which was not modified since 8 Oct 2018. Also requirements.txt is updated.
