### ISSUE TITLE
create bucket when doesn't exist

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#129]
To enhance user experience, I suggest a simple change on pywren's init:
if the bucket name (which provided by config) doesn't exist - pywren will create it automatically. Also it will be convenient if pywren will create a default bucket name if wasn't provided at all.

what do you think?

**Comment by gilv** [comment]
@omerb01 it's ok to have it...but this should be configurable option, like "storage.bucket.auto.create = true / false". The default is better to be "false"

**Comment by omerb01** [comment]
due to the fact that bucket name is unique over IBM Cloud, this suggestion isn't relevant.
