### ISSUE TITLE
add more options for IBM Cloud Functions connection

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#130]
IBM Cloud provides lots of services which can work together in various ways.
currently, to connect to IBM Cloud Functions you have to provide the basic API key which is a specific api key for this service.
IBM Cloud allows to use IAM keys which directed to multiple services so you don't need a dedicated api key for each service.
When using multiple services of IBM Cloud it will be more convenient if there will be one IAM key for all services including PyWren so I suggest to add an option to connect everything by IAM key.

**Comment by gilv** [comment]
@omerb01 this is good...but this should be opened against IBM Cloud, not against PyWren ;)

**Comment by omerb01** [comment]
@gilv IBM Cloud does already has this option - you can also connect to Cloud Functions with an aim key, but PyWren doesn't support it currently.

**Comment by JosepSampe** [comment]
@omerb01 Just out of curios... Does IAM key work with COS account?

**Comment by omerb01** [comment]
@JosepSampe I tried to figure out some info about all that credentials logic in IBM Cloud... actually I'm quite confused: I do know that people use IBM Cloud services by IAM keys and direct them to access multiple services at once. For some reason I didn't find any info about IAM Key usage with Cloud Object Storage - maybe it is an elementary service so you don't need a dedicated key - currently we connect to this service by a global api key to IBM Cloud

**Comment by JosepSampe** [comment]
@gilv This issue is already done with the `iam_connector`, right?
