### ISSUE TITLE
Issues with updating runtimes

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#136]
I did very simple test:
1. Modified jobrunner.py, by adding new print statement
2. pip install -U .
3. cd /runtime/; ./deploy_runtime create cactusone/pywren-dev:3.6
4. my CONFIG file has “action_name : pywren-dev_3.6” in “ibm_cf” section
5. run iunitest python pywren_ibm_cloud/testpywren.py test_map_reduce_cos_key_one_reducer_per_object

When i observed logs i didn't saw my new print statement in jobrunner.py

@JosepSampe am i doing something wrong? I think it related that new runtime management you added recently? thanks

**Comment by gilv** [comment]
@JosepSampe i assume my mistake is that i need to use  ‘runtime’ : ‘cactus/pywren-dev:3.6’ and not "action_name" ? But even i didn't why the runtime which is used by PyWren is not updated automatically with the changes? I thought it deploy runtime on the fly, no?

**Comment by JosepSampe** [comment]
@gilv Yep, you need to specify in config (or config file): ` ‘runtime’ : ‘cactus/pywren-dev:3.6’`.
After you run `3. cd /runtime/; ./deploy_runtime create cactusone/pywren-dev:3.6`, The runtime action is updated, so it should use the new docker image. Maybe you have to wait till CF cluster detects that you modified the image...

**Comment by JosepSampe** [comment]
@gilv With #139 the issue should be fixed.
Note that I changed the **create** command to **build**, so if you want to build your Dockerfile, you have to run: `./deploy_runtime build cactusone/pywren-dev:3.6`
