### ISSUE TITLE
do we need tornado?

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#141]
https://github.com/pywren/pywren-ibm-cloud/blob/master/pywren_ibm_cloud/libs/ibm_iam/iam_connector.py

@JosepSampe can you please tell me if we need tornado? if yes, should we add it to dependencies? if not, do you have suggestions for alternatives? thanks

**Comment by JosepSampe** [comment]
@gilv We have 2 options: Use tornado and add it to dependencies, or move to another library like **requests** or **httl.client** as in cf_connector.py.

The question is: Did you use tornado for some reason?

**Comment by gilv** [comment]
@JosepSampe actually there is no reason for tornado... seems  landed in the code without me noticing it. So i guess you suggest then to remove this package...right?

**Comment by JosepSampe** [comment]
@gilv Yep, I will change it to **requests** or **http.client**

**Comment by JosepSampe** [comment]
@gilv Fixed in #140
