### ISSUE TITLE
Add entry_points for `runtime/deploy_runtime` into `setup.py` installation.

### ISSUE THREAD

**Issue by spitfiredd** [pywren/pywren-ibm-cloud#146]
I would like to have access to the deploy_runtime cli when I install pywren from pip.  Is it possible to make `runtime/deploy_runtime` an `entry_point` in the `setup.py` as described [here](https://click.palletsprojects.com/en/7.x/setuptools/#setuptools-integration)?

Rationale:

Suppose I have an application with the following structure,

```
my-app/
    src/
    runtimes/
        Dockerfile
        requirements.txt
```

It would be convenient to build a custom runtime per application, e.g.

   ```
   (.venv) ~/my-app/runtimes>deploy-runtime build "docker-username/my-runtime:tag"
   ```
 Currently, the runtime folder isn't a package so it isn't being installed via pip, so If I want to update a runtime for an application, I have to clone the pywren repo into a separate folder and then update/build a custom runtime from there.

**Comment by JosepSampe** [comment]
Done in #148.

The script is called `pywren-runtime`
