### ISSUE TITLE
PyWren installation inside docker

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#151]
I think there is something wrong with our PyWren installation runtime "for developers".
usually, when an executor is created, its runtime is installed with the current PyWren's code. the only reason that it won't install runtime is if the same PyWren version has been already installed but in development we don't change pywren's version so the situation here is that PyWren's code in local machine is different from PyWren's code in the runtime.

The solution I found for this issue is to clean all the runtimes by: `./pywren_runtime clean`
but it should be automatically, maybe we need to add automatic versions tagging in development.

**Comment by JosepSampe** [comment]
@omerb01 The idea behind automatic runtime deployment was to ease common users to deploy the runtime without using the script.

I think that we cannot identify if someone that uses PyWren is a developer or not, so if we want to make it automatic, it will add an overhead to identify if the code was changed or not. As a developer, in my case I always use the deployment script (from the beginning of the beginnings). I think that using the script gives us more control of what we update as a developers.

If you only use one runtime with different memory sizes, I think that it is not needed to clean everything, you can only update the runtime that you are using, such as: `./pywren_runtime update jsampe/pywren:3.6`

**Comment by omerb01** [comment]
@JosepSampe couple of questions :)
1. on which script are you talking about? can you refer a link for it?
2. is there a way to update the default runtime also?
thanks

**Comment by JosepSampe** [comment]
@omerb01
1. I'm referring to the same script you use to `clean` ;) https://github.com/pywren/pywren-ibm-cloud/blob/master/runtime/pywren_runtime

2. To update the default runtime: `./pywren_runtime update default`. However, if you want to update multiple runtimes at a time, it is not yet implemented.  Maybe we can allow something like: `./pywren_runtime update default jsampe/pywren:3.6 omerb01/pywren-omer-runtime:3.6` to update multiple runtimes at a time, and also: `./pywren_runtime update all`.

**Comment by omerb01** [comment]
Thanks! :)
