### ISSUE TITLE
how to share data between actions with files in the runtime

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#152]
I have a question about something I haven't fully understood yet ;)
I want to implement something with the logic below:
```python
def main_func(args):
    open('omer.txt', 'w').write('1234')

def sub_func1(args):
    return open('omer.txt').read()

def sub_func2(args):
    return open('omer.txt').read()

def sub_func3(args):
    return open('omer.txt').read()

pw = pywren.ibm_cf_executor()

pw.map(main_func, [''])
pw.get_result()

pw.map(sub_func1, [''])
pw.map(sub_func2, [''])
pw.map(sub_func3, [''])
print(pw.get_result())
```
is this a reliable approach? when `omer.txt` will be removed?
are there specific directories in the runtime which reset their content?
I tested some different code scripts and found that sometimes it works and sometime it don't.

**Comment by JosepSampe** [comment]
@omerb01 It is all based of warm containers. While the container is warm, it keeps all the files you wrote within it. You can write files wherever you want, although it is common to write them into `/tmp`

For example, if you run `main_func()` 1000 times with map(), it will start 1000 containers, and then the function will write `omer.txt` within them. These containers are kept warm during aprox 10 minuts, so during this time, if you launch `sub_func1`, `sub_func2` and `sub_func3` (no more than 1000 times in total), all them will be able to read the file. 

In contrast, if you wait 10 minutes from `pw.map(main_func, [''])` to `pw.map(sub_func1, [''])`, then all the warm containers will be killed, meaning that all the files you wrote will no longer be available, as when a container is killed all the information within it is lost.

It should be note that now, for some internal CF issue, there are times that, even having enough warm containers after calling the `main_func()`, CF starts a new cold container from scratch when you call `sub_func1()`, so you probably get a small percentage of functions that can't get the file even without waiting these 10 minutes.

**Comment by omerb01** [comment]
@JosepSampe Thanks! so for now, we can't relay on this approach.
@gilv FYI about the CF internal issue
