### ISSUE TITLE
Minor issue with get_result() method

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#157]
when I run:
```python
import pywren_ibm_cloud as pywren

def my_map_func(args):
    pass

def my_reduce_func(results):
    return 'reduce output'

pw = pywren.ibm_cf_executor()
pw.map_reduce(my_map_func, range(3), my_reduce_func)
print(pw.get_result())
```
the output is:
```
[None, None, None, 'reduce output']
```
and it should be only the output from the reducer.

**Comment by omerb01** [comment]
@JosepSampe I noticed that if I run the code above on Python 3.6.7, it still returns:
```
[None, None, None, 'reduce output']
```
but on Python 3.6.0 it's fine.

**Comment by gilv** [comment]
@JosepSampe year...I reconfirm. We have issues in 3.6.7 and not 3.6.0... can you spot what is wrong? perhaps some syntax we use in the code?

**Comment by gilv** [comment]
@JosepSampe in 3.6.7 we are getting

--> 149     inner_func_name, inner_futures = pw.get_result(futures)
    150     append_pywren_stats(segment_spectra_chunk.__name__, 1024, futures[:-1])
    151     append_pywren_stats(inner_func_name, 512, inner_futures)

ValueError: too many values to unpack (expected 2)

**Comment by JosepSampe** [comment]
@gilv @omerb01 I have python 3.6.7 in my machine and it works as expected... also works fine with 3.7 .. very weird, it should work in the same way with any of these python versions. Do you have the package updated in any of them? maybe in one python version you are using an old PW version

**Comment by gilv** [comment]
@JosepSampe I will re-test with new runtime

**Comment by gilv** [comment]
@JosepSampe hmmm.... no more issues ;)
