### ISSUE TITLE
memory management issue in "reduce" executions

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#161]
I try to optimise some code in terms of memory usage and I think I've discovered an issue with deleting "results" list in reduce funcs. If I try to delete it, I think it still stays on the runtime.

For example:
```python
import pywren_ibm_cloud as pywren

def my_map_func(args):
    memo = '0' * 50 * 1024 ** 2  # 50mb
    return memo

def my_reduce_func(results):
    del results
    memo = '0' * 100 * 1024 ** 2  # 100mb
    return 'SUCCESS'

pw = pywren.ibm_cf_executor(log_level='DEBUG')
pw.map_reduce(my_map_func, range(2), my_reduce_func)
print(pw.get_result())
```
I get here memory error in the reduce function and it doesn't make sense (256mb runtime memory)

**Comment by JosepSampe** [comment]
@omerb01 you can use this to see an estimated memory usage:
```
import pywren_ibm_cloud as pywren
from pywren_ibm_cloud.utils import get_current_memory_usage

def my_map_func(args):
    memo = '0' * 50 * 1024 ** 2  # 50mb
    return memo

def my_reduce_func(results):
    print(get_current_memory_usage())
    del results
    print(get_current_memory_usage())
    memo = '0' * 100 * 1024 ** 2  # 100mb
    return 'SUCCESS'

pw = pywren.ibm_cf_executor(log_level='DEBUG')
pw.map_reduce(my_map_func, range(2), my_reduce_func)
print(pw.get_result())
```
And yep, it seems that reduce func keeps results variable in memory

**Comment by omerb01** [comment]
@JosepSampe great feature ;)

**Comment by JosepSampe** [comment]
It should be investigated. `results` variable are sent to the function by using **kwargs, and seems that when you delete `results`, it only deletes a reference to the memory position, no the actual data.

Some links:
https://stackoverflow.com/a/41461511
https://stackoverflow.com/questions/6146963/when-is-del-useful-in-python/6146992#6146992

**Comment by omerb01** [comment]
@JosepSampe I think it's ok, the issue here is that there are some references to `results` list somewhere so when we delete it, the actual data isn't deleted. is there a possible way that only results list will point to that data?

**Comment by JosepSampe** [comment]
I added a fix here: https://github.com/pywren/pywren-ibm-cloud/pull/159/commits/3e77746b877acbc2cf3f52a5e1a16e16554e3496

When merged, use `results.clear()` instead of `del results` to free the memory

**Comment by JosepSampe** [comment]
@omerb01 Can you test if it works for you?

**Comment by omerb01** [comment]
@JosepSampe works, thanks
