### ISSUE TITLE
README link is wrong

### ISSUE THREAD

**Issue by davetropeano** [pywren/pywren-ibm-cloud#165]
The `README.md` file shows the `config/default_config.yaml.template` file and in the `ibm_cf` section it has:

```
ibm_cf:
    # Obtain all values from https://cloud.ibm.com/openwhisk/learn/api-key
    endpoint    : <HOST>  # make sure to use https:// as prefix
    namespace   : <NAMESPACE>
    api_key     : <API_KEY>
```

the link https://cloud.ibm.com/openwhisk/learn/api-key returns a 404. 

Perhaps this is a better URL to reference? 

https://cloud.ibm.com/docs/openwhisk?topic=cloud-functions-namespaces

**Comment by JosepSampe** [comment]
Fixed in #166 
The correct link is: https://cloud.ibm.com/openwhisk/namespace-settings
It was correct in https://github.com/pywren/pywren-ibm-cloud/blob/master/docs/configuration.md
Thanks for reporting @davetropeano
