### ISSUE TITLE
pywren_runtime script rases error

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#174]
when I try to deploy a new environment by:
```
./pywren_runtime build omerb01/pywren-omer-runtime:3.6
```
I get:
```
AttributeError: 'Compute' object has no attribute 'build_runtime'
```

**Comment by JosepSampe** [comment]
Fixed in #175

**Comment by omerb01** [comment]
@JosepSampe another minor thing. the docker file location should be configured to be inside `ibm_cf` folder. when I try to build a docker image, I get:
```
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /Users/omerbelh/IdeaProjects/WORK/pywren-ibm-cloud/runtime/Dockerfile: no such file or directory
```

**Comment by JosepSampe** [comment]
@omerb01 If you have pywren installed, can you try this: https://github.com/pywren/pywren-ibm-cloud/issues/146?

**Comment by omerb01** [comment]
@JosepSampe what do you mean? I use `pywren_runtime` script to build or update Docker images

**Comment by JosepSampe** [comment]
@omerb01 If you have pywren installed, you should have the script installed as a unix script, so you can run it from any folder you want, for example, from within `ibm_cf` folder.

**Comment by omerb01** [comment]
@JosepSampe oh, I have just tried to following command:
```
pywren-runtime build omerb01/pywren-omer-runtime:3.6
```
and it failed by this exception:
```
pkg_resources.ContextualVersionConflict: (urllib3 1.25.3 (/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages), Requirement.parse('urllib3<1.25,>=1.20'), {'ibm-cos-sdk-core'})
```
actually, I don't think its a good approach rather than operate this script from inside `pywren_ibm_cloud` module, its quite confusing.
Also, it isn't convenient to navigate into `ibm_cf` folder everytime when I want to seek the Dockerfile (save it in the root directory will be messy). I suggest to add a flag input describing where the Dockerfile is.

**Comment by JosepSampe** [comment]
@omerb01 Regarding exception, I think you have some package conflict in your .pyenv, so check it.

I added a flag into the deployment script to specify the location of the Dockerfile, I will submit a pull request earlier. However, based on the comments of this #146, I think it is also a good approach to navigate into the folder where you have your Dockerfile to build it. So now we support both approaches as native `docker build` tool does.

**Comment by JosepSampe** [comment]
@omerb01 Did you try ` ./pywren_runtime -f` parameter added here #176?

**Comment by omerb01** [comment]
@JosepSampe yes, everything works for me (also fixed my exception)
thanks!
