### ISSUE TITLE
tests doesn't work anymore in master branch

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#177]
I updated to most recent master branch

python pywren_ibm_cloud/tests.py 
Uploading test files...
EEEEEEEEEEEEE
======================================================================
ERROR: test_call_async (__main__.TestPywren)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pywren_ibm_cloud/tests.py", line 182, in test_call_async
    pw = pywren.ibm_cf_executor(config=CONFIG)
  File "/Users/aaa/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/executor.py", line 53, in __init__
    self.config = default_config(config)
  File "/Users/aaa/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/config.py", line 109, in default_config
    cb_config.load_config(config_data)
  File "/Users/aaa/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/compute/backends/ibm_cf/config.py", line 50, in load_config
    if set(required_parameters_1) <= set(config_data['ibm_cf'][region]) or \
TypeError: 'int' object is not iterable

**Comment by gilv** [comment]
@JosepSampe was something changed with respect to config files?

**Comment by omerb01** [comment]
@gilv I ran all tests successfully with @JosepSampe 's recent update, maybe is there a change in your local machine?

**Comment by gilv** [comment]
I did git 

     pull origin master
     pip install -U .
     python/pywren-ibm/cloud tests.py

@omerb01

**Comment by JosepSampe** [comment]
@gilv Theoretically it should work all as usual. Let me check it

**Comment by gilv** [comment]
@JosepSampe PyWren looks for CB_CONFIG system variable while in the past it looked for PYWREN_CONFIG_FILE variable

**Comment by gilv** [comment]
@JosepSampe I actually confused...some looks for CB_CONFIG, some for PYWREN_CONFIG...

def get_default_config_filename():
    """
    First checks .pywren_config
    then checks PYWREN_CONFIG_FILE environment variable
    then ~/.pywren_config
    """
    if 'PYWREN_CONFIG_FILE' in os.environ:
        config_filename = os.environ['PYWREN_CONFIG_FILE']
        # FIXME log this

    elif os.path.exists(".pywren_config"):
        config_filename = os.path.abspath('.pywren_config')

    else:
        config_filename = get_default_home_filename()

    return config_filename


def default_config(config_data=None):
    """
    First checks .pywren_config
    then checks PYWREN_CONFIG_FILE environment variable
    then ~/.pywren_config
    """
    if not config_data:
        if 'CB_CONFIG' in os.environ:
            config_data = json.loads(os.environ.get('CB_CONFIG'))
        else:
            config_filename = get_default_config_filename()
            if config_filename is None:
                raise ValueError("could not find configuration file")

            config_data = load(config_filename)

    if 'pywren' not in config_data:
        raise Exception("pywren section is mandatory in the configuration")

**Comment by JosepSampe** [comment]
@gilv One is `PYWREN_CONFIG_FILE` which is configurable by the user and indicates the location of the config file. The other is `CB_CONFIG` which is internally managed by pywren. 

But the error is not here, I think you may have an error in your` .pywren_config` file structure. Can you send me it?

**Comment by gilv** [comment]
The error is because I  has "action_memory" and "action_name" in "ibm_cf" section.
