### ISSUE TITLE
bugs related to runtimes deployment

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#178]
I found 2 issues related to runtimes deployments, I am not sure if these issues come from CF or from PyWren.
1. when I try to build a new docker env on an **already existed** env - PyWren serialise every additional module that was added to the new runtime and not in the previous runtime. notice that even though the new modules were installed, PyWren serialise them.
2. when I remove lines like `RUN pip install ...` and build a new docked env on an **already existed** env, I expect that these modules will be uninstalled from the env, but they are actually still there. I tested it with the module `colorama` - once I build the runtime with `RUN pip install colorama`, it stays in the env forever.

**Comment by gilv** [comment]
@JosepSampe can you please let us know what you think about it? thanks

**Comment by JosepSampe** [comment]
@gilv @omerb01 Checking it

**Comment by JosepSampe** [comment]
@gilv @omerb01 After some tests, it seems to be due to this: https://github.com/pywren/pywren-ibm-cloud/issues/147

In any case, I'm trying to find a way to solve the issue from PyWren side

**Comment by omerb01** [comment]
@JosepSampe I am not sure that the first issue I mentioned is related to CF, actually its quite confusing. I want to emphasise that the modules are installed successfully the issue is that PyWren decides to serialise them.
some thoughts that come to my mind are about this part:
https://github.com/pywren/pywren-ibm-cloud/blob/2b542c2ef705d04148ad9653e4536bee83ea4f50/pywren_ibm_cloud/runtime/deploy_utils.py#L71
is `runtime_meta` the most updated one? does `generate_runtime_meta()` method use CF to extract all preinstall modules?

**Comment by JosepSampe** [comment]
@omerb01 The problem is that we use a function to extract `runtime_meta`, and due #147, it always return the same `runtime_meta`. Is for this that if you build the runtime with different packages, `generate_runtime_meta()` always returns the modules that were installed the first time you built the runtime

**Comment by omerb01** [comment]
@JosepSampe can you explain in details all buggy requests for CF we use in PyWren?
including #147 . thanks

**Comment by JosepSampe** [comment]
@omerb01 Each time you update the docker-image in the docker hub, a different hashtag is created (sha256). With this, if you know the hashtags, you can use a specific docker image version even if you updated it. For example, refer to this: https://stackoverflow.com/questions/32046334/where-can-i-find-the-sha256-code-of-a-docker-image)

So my feeling is that when you create an action in the CF service the first time, it is attached to a Docker image by using the docker image hashtag, and then, for some internal CF issue (or for something I don't know), this attachment prevails over time and the hashtag is never updated to the new version, even if you delete the action and recreate it again. This causes the action to use always the same docker image version with the same packages.

**Comment by JosepSampe** [comment]
I think that my previous feelings were correct, and writing the previous post I realized that I could write the desired sha256 digest when I update the action in the CF service. I did a test and I if i write the latest sha256 digest It seems to work, and this issue and #147 disappears. I need to verify this and run more tests, but I think I can solve this from PyWren side.

**Comment by JosepSampe** [comment]
@omerb01 I think we should assume that in IBM CF, now runtimes must be always tagged with new version number for every update, so this issue is no longer PyWren related.
