### ISSUE TITLE
some ignored errors regrading urllib3 module

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#186]
noticed that sometimes, when I wait for invocations to be done by `get_result()`, I get traceback messages regarding ignored exceptions.
for example:
```
Exception ignored in: <generator object urlsplit.<locals>.<genexpr> at 0x12e968620>
Traceback (most recent call last):
  File "/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/urllib/parse.py", line 423, in <genexpr>
    if not rest or any(c not in '0123456789' for c in rest):
SystemError: error return without exception set
```
my local urllib3 version is 1.24.3.
I found that if I update it to the latest one (1.25.x) I get no ignored errors, but then I get context conflict exceptions.
I think that we need to update PyWren's urllib3 to prevent these ignored exceptions during PyWren's process

**Comment by JosepSampe** [comment]
@omerb01 So finally, which version are you using? In my case I've never got this error, I'm using 1.24.1.

**Comment by omerb01** [comment]
@JosepSampe I use 1.24.3
I'll try to use 1.24.1 also and see if there are any exceptions like this.

according to: https://stackoverflow.com/questions/37419362/python-requests-ignore-exceptions-and-errors-while-connecting-to-proxy-server
sometimes, there might be too many requests on a timestamp which causes these exceptions.
its important to say that it doesn't damage the execution at all, only shown as an ignored exception.

**Comment by gilv** [comment]
@omerb01 @JosepSampe I am using 1.25.3...may be we need to add this version to requirements?

**Comment by JosepSampe** [comment]
@gilv 1.25.3 solved your issue?

**Comment by omerb01** [comment]
@JosepSampe I tried to use 1.24.1 (the same version as yours) and nothing has been changed.
Updated for 1.25.3 , will test it and update whether it helped or not.

**Comment by omerb01** [comment]
after some tests I think it isn't PyWren related
