### ISSUE TITLE
exception when building new runtime

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#188]
./pywren_runtime build aaa/pywren-metabolomics:3.6.11
DEBUG:pywren_ibm_cloud.libs.ibm_cloudfunctions.client:IBM CF init for namespace: pywren_dev_us_east
DEBUG:pywren_ibm_cloud.libs.ibm_cloudfunctions.client:IBM CF init for host: https://us-east.functions.cloud.ibm.com
DEBUG:pywren_ibm_cloud.libs.ibm_cloudfunctions.client:IBM CF user agent set to: python-requests/2.22.0 pywren-ibm-cloud/1.0.18-snapshot
INFO:pywren_ibm_cloud.compute.backends.ibm_cf.ibm_cf:PyWren v1.0.18-snapshot init for IBM Cloud Functions - Namespace: pywren_dev_us_east - Region: us_east
INFO:pywren_ibm_cloud.compute.backends.ibm_cf.ibm_cf:Creating a new docker image from Dockerfile
INFO:pywren_ibm_cloud.compute.backends.ibm_cf.ibm_cf:Docker image name: aaa/pywren-metabolomics:3.6.11
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /Users/xyz/Dev/pywren-ibm-cloud/runtime/Dockerfile: no such file or directory

it should look for runtime/ibm_cf/ Dockerfile and not runtime/Dockerfile

**Comment by gilv** [comment]
@JosepSampe need your magic touch here...

**Comment by omerb01** [comment]
@gilv see #174

**Comment by gilv** [comment]
@omerb01 then I guess documentation is not updated...can you please update it? this -f is not documented, unless I missed it somewhere

**Comment by JosepSampe** [comment]
@gilv As @omerb01 said, you can write "docker build **-f**" parameter to specify the location of your Dockerfile. This parameter was recently added since now we support multiple compute backends, and consequently we can have multiple folders within "runtime" folder.
