### ISSUE TITLE
Pickle exception bug when using pandas

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#189]
I think I have discovered a bug while using pandas in PyWren.
made an example to represent it easily:
```python
import pywren_ibm_cloud as pywren
import pandas as pd
import pickle

def segment_centr_df(args, ibm_cos):
    centr_df = pickle.loads(ibm_cos.get_object(Bucket='omerpublic', Key='omer/centr_df.pickle')['Body'].read())
    first_peak_df = pickle.loads(ibm_cos.get_object(Bucket='omerpublic', Key='omer/first_peak_df.pickle')['Body'].read())

    centr_segm_df = pd.merge(centr_df, first_peak_df[['formula_i', 'segm_i']],
                             on='formula_i').sort_values('mz')

    print(centr_segm_df)

pw = pywren.ibm_cf_executor(runtime='omerb01/pywren-omer-runtime:3.6.6' ,runtime_memory=4096)
futures = pw.map(segment_centr_df, '')
pw.get_result(futures)
```
when CF operates `pd.merge`, an exception is raised:
```
--> Exception: PyWren was unable to pickle the exception, check function logs
```
and if I check activation logs, I don't find anything else except this pickle exception.
its important to note that if I download `centr_df` and `first_peak_df` to my local machine and operate the same logic, everything is fine without any exception.

**Comment by JosepSampe** [comment]
@omerb01 For some reason regarding pickle package, it is not possible to pickle some exceptions from **pandas** and **numpy** (and maybe other) libraries, if for this the exception: `--> Exception: PyWren was unable to pickle the exception, check function logs`. 

But if it works in your local machine, I need to know what produces the exception and why it is not printed in activation logs. Can you send me the `centr_df.pickle` and `first_peak_df.pickle` files?

**Comment by gilv** [comment]
@JosepSampe @omerb01 right..exception happens in the merge method of Pandas and then it's not thrown. So there is nothing wrong in PyWren. The strange behaviour we observe is that merge fails when we run segment_centr_df  from PyWren and same method works locally without issues...

**Comment by omerb01** [comment]
@JosepSampe I edited the code above and changed the bucket to `omerpublic` which is a public one. you can run this code and see what happens.

**Comment by gilv** [comment]
@JosepSampe FYI I also updated versions in the Docker image and it still fails in merge method.
This is Docker image I am using
``  
FROM ibmfunctions/action-python-v3.6:master

RUN pip install cpyImagingMSpec==0.2.4
RUN pip install pandas==0.25.1
RUN pip install pyImagingMSpec==0.1.4
RUN pip install pyMSpec==0.1.2
RUN pip install cpyMSpec==0.3.5
RUN pip install pyimzML==1.2.5
RUN pip install msgpack-numpy==0.4.4.3
RUN pip install metaspace2020
RUN pip install numpy --upgrade
RUN pip install python-dateutil --upgrade
RUN pip install scipy --upgrade
RUN pip install pytz --upgrade
``

**Comment by JosepSampe** [comment]
@omerb01 @gilv After some test, I realized that this is not a pickling exception. In fact there is no exception in the code. The error comes from that the jobrunner process (that runs the function) is suddenly killed for some reason, and the logs does not provide information on why the process is killed.

For example, in my case:
```
Activation: 'omerb01_pywren-omer-runtime_3.6.6_4096MB' (df961021deb94c26961021deb9fc2608)
[
    "2019-08-26T13:13:50.863549Z    stdout: [INFO] __main__: Starting IBM Cloud Function execution",
    "2019-08-26T13:13:50.864267Z    stdout: [INFO] handler: Execution ID: 0f16-4d74/M000/00000",
    "2019-08-26T13:13:50.872743Z    stdout: [INFO] handler: Starting JobRunner process",
    "2019-08-26T13:13:50.880782Z    stdout: [INFO] JobRunner: Started",
    "2019-08-26T13:13:51.589237Z    stdout: [INFO] JobRunner: Function: Going to execute 'segment_centr_df()'",
    "2019-08-26T13:13:51.589267Z    stdout: ---------------------- FUNCTION LOG ----------------------",
    "2019-08-26T13:14:06.896430Z    stdout: 588.4MiB",
    "2019-08-26T13:14:10.760964Z    stdout: [INFO] handler: Finished JobRunner process",
    "2019-08-26T13:14:10.761249Z    stdout: [ERROR] handler: There was an exception: ('UNKNOWNERROR', 'Jobrunner process was suddenly killed without response')",
    "2019-08-26T13:14:10.808378Z    stdout: [INFO] handler: Storing execution stats - status.json - Size: 1.1KiB"
]
```

As you can see, the handler prints "Finished JobRunner process", however the function didn't finish successfully since it didn't `print(centr_segm_df)`. It should be noted that this behavior happend 3 monts ago when a function raised an OutOfMemory error, where the jobrunner process was also killed in the same way as now with this issue. However, I think now it is not an OOM error.

@omerb01  I did some changes in #193. When merged, can you try it again and share your logs?

**Comment by JosepSampe** [comment]
@omerb01 @gilv After some more tests, I think that it is an OOM issue. For some reason, CloudFunctions behaves in a different way regarding OOM error when you use >2048MB of memory. So if we use 3GB or 4GB of memory, CF behaves as it did 3 months ago where only the Jobrunner process was killed, and not the whole container as it happens now.

**Comment by gilv** [comment]
@omerb01  @JosepSampe I also think it's out of memory issue

**Comment by omerb01** [comment]
@gilv @JosepSampe thanks, regarding #144 , we can close this issue.
