### ISSUE TITLE
chunking large files should also provide part number as an input to the map

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#192]
Assuming we chunk large file and there are 10 chunks. Each 
map has signature with the pattern of

```
map(key, data_stream, ibm_cos):
```

However while key is the same object name, data_stream is the relevant chunk

We need to extend map so that it will also receive chunk id number, something like

```
map(key, data_stream, chunk_id, ibm_cos):
```

**Comment by gilv** [comment]
This actually not only related chunks...
also input as array, should provide each Map not only the value but also index number from the array

**Comment by JosepSampe** [comment]
@gilv Maybe instead of this: `map(key, data_stream, chunk_id, ibm_cos)`, and this: `map(key, data_stream, index, ibm_cos)`, we can set a more generic parameter to cover both cases, something like: `map(key, data_stream, id, ibm_cos)`. What do you think? any suggestion?

**Comment by gilv** [comment]
@JosepSampe yeap...."id" is what I had in mind actually. Whenever PyWren partition some data, an optional parameter to map, should be the id of the part..index in array, chunk number if it's COS, etc.

**Comment by omerb01** [comment]
@JosepSampe @gilv I think it will be cleaner if we will define a new object.
I suggest something like: `map_function(input_data, PyWren_data)`.
`input_data` will be input keys from the user, `PyWren_data` will be a class which maintained by PyWren that provides useful features like ibm_cos, chunk_id, internal_storage, key, bucket, etc

**Comment by gilv** [comment]
@omerb01 we already have a new object...."cloud object"

**Comment by omerb01** [comment]
@gilv if I understood it right, cloud objects intended for something different, to prevent maintaining keys in cos while using pywren

**Comment by JosepSampe** [comment]
@gilv Do you need **chunk_id** for some reason? or only for logging? becasue in logs you already have the id, for example:
```
Activation: 'ibmfunctions_action-python-v3.6_256MB' (2048b149380948da88b1493809e8da82)
[
    "2019-08-27T09:40:06.178776Z    stdout: [INFO] __main__: Starting IBM Cloud Function execution",
    "2019-08-27T09:40:06.179315Z    stdout: [INFO] handler: Execution ID: 50f2-4d3e/M000/00000",
    "2019-08-27T09:40:06.189037Z    stdout: [INFO] handler: Starting JobRunner process",
    "2019-08-27T09:40:06.195153Z    stdout: [INFO] JobRunner: Started",
    "2019-08-27T09:40:06.334848Z    stdout: [INFO] JobRunner: Function: Going to execute 'my_function()'",
    "2019-08-27T09:40:06.334880Z    stdout: ---------------------- FUNCTION LOG ----------------------",
    "2019-08-27T09:40:08.337515Z    stdout: ----------------------------------------------------------",
    "2019-08-27T09:40:08.337571Z    stdout: [INFO] JobRunner: Function: Success execution",
    "2019-08-27T09:40:08.337958Z    stdout: [INFO] JobRunner: Finished",
    "2019-08-27T09:40:08.341962Z    stdout: [INFO] handler: Finished JobRunner process",
    "2019-08-27T09:40:09.415324Z    stdout: [INFO] handler: Execution stats sent to rabbitmq - Size: 485.0B",
    "2019-08-27T09:40:09.471410Z    stdout: [INFO] handler: Storing execution stats - status.json - Size: 485.0B"
]
```

you can see: `Execution ID: 50f2-4d3e/M000/00003`, where the first part (50f2-4d3e) is the **Executor ID**, the second part (M000) is the **Job ID**, and the third part (00003) is the **id** we are talking about in this discussion.

**Comment by omerb01** [comment]
@JosepSampe I also think that we need to extract an execution id from inside pywren for a generic map function. currently I use a lot unique strings that I extract from `key` parameter by split manipulations and it is quite messy.

**Comment by JosepSampe** [comment]
@omerb01 @gilv I already have the `id` added as an optional parameter.

In addition, similar to what Omer suggested above, I also suggest to group `bucket`, `key`, `data_stream` and `url` in one unique parameter. Because now we have 3 possible function signatures for data processing, and maybe, as Lachlan also said, is a bit confusing:

-To process a bucket:
`my_map_function(bucket, key, data_stream)`
-To process an object(s):
`my_map_function(key, data_stream)`
-To process an url(s):
`my_map_function(url, data_stream)`

So my suggestion is to put all of these parameters into one, and then PyWren will internally do the magic, something like:
```
def my_map_function(obj):
    print(obj.bucket)
    print(obj.key)
    print(obj.data_stream.read())
```

What do you think?

**Comment by omerb01** [comment]
@JosepSampe sounds great

**Comment by JosepSampe** [comment]
@gilv @omerb01 I added the 'obj' optional arg for the functions in #194 as we discussed above. Consequently, I deleted `bucket`, `key `and `data_stream` args. So now, when you want to process objects from the object store you must specify 'obj' arg in the function. With the 'obj' arg you can access to all the information of the COS object, including the number of partition:

```
def my_map_function(obj):
    print(obj.bucket)
    print(obj.key)
    print(obj.data_stream.read())
    print(obj.part)
    print(obj.data_byte_range)
    print(obj.chunk_size)
```

To process URLs, I leave `url `parameter, but now it is also a class:
```
def my_map_function(url):
    print(url.path)
    print(url.data_stream.read())
    print(url.part)
    print(url.data_byte_range)
    print(url.chunk_size)
```

**Comment by JosepSampe** [comment]
@omerb01 Can you adapt tests to these changes?
