### ISSUE TITLE
obj, url should be documented in documentation

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#195]
Per https://github.com/pywren/pywren-ibm-cloud/issues/192 we need to document all fields of obj and url, for example all those fields of obj should be documented, with description and examples

obj.bucket
obj.key
obj.data_stream.read()
obj.part
obj.data_byte_range
obj.chunk_size

the same for url

**Comment by JosepSampe** [comment]
@gilv Added in #213
