### ISSUE TITLE
Execution of single file or list of files not working

### ISSUE THREAD

**Issue by ManuelEberhardinger** [pywren/pywren-ibm-cloud#215]
When I try to run PyWren again on failed actions which exited unexpectedly, I get an error that the file is not found in the COS-Bucket even though it was executed before.

example: 
```
pw = pywren.ibm_cf_executor(config=config)
try:
    pw.map(my_map_function, ['ibm_cos://01-10-2019/1569902700000.csv', 'ibm_cos://01-10-2019/1569892800000.csv'])
    result = pw.get_result()
    print("Execution completed")
except Exception as e:
    print (e)
finally:    
    pw.clean()
```

I get this error:
```
PyWren v1.0.20 init for IBM Cloud Functions - Namespace: pywren-test - Region: us_east
ExecutorID 243b-42b8 | JobID M000 - Selected Runtime: ibmfunctions/action-python-v3.6 - 256MB 
Object key "/1569902700000.csv" does not exist in "01-10-2019" bucket
ExecutorID 243b-42b8 - Cleaning temporary data
```

I think the problem is the parsing of the filenames as the slash is still in the object key.

**Comment by JosepSampe** [comment]
@ManuelEberhardinger This is an issue already fixed in master branch, but no revision still created.
@gilv may we need to create a new release?

**Comment by JosepSampe** [comment]
@ManuelEberhardinger you can already use 1.1.1 release

**Comment by ManuelEberhardinger** [comment]
@JosepSampe thanks, then I close this issue.
