### ISSUE TITLE
Add user agent for all COS operations

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#22]
We need to add custom user-agent  = PyWren for all operations to COS.

**Comment by mbehrendt** [comment]
out of curiosity -- what is this needed for? E.g. what does not work without this?

**Comment by gilv** [comment]
this is common approach, to track clients that initiate requests. it's not mandatory, just nice to have

**Comment by mbehrendt** [comment]
ok, thank you -- that's what i thought

**Comment by gilv** [comment]
resolved https://github.com/pywren/pywren-ibm-cloud/commit/39af0d218a64261c2a5fa15f440a990efd3a2108
