### ISSUE TITLE
Update Knative-Pywren tutorial

### ISSUE THREAD

**Issue by lchu-ibm** [pywren/pywren-ibm-cloud#221]
Hi, I have been working on putting one of our projects on CF+pywren for a while and we have recently decided to switch to Knative cluster as the current prod cluster is not suitable for our scenario (as discussed with Gil and Michael).

I have been following these two tutorials:
1. Knative CF without using pywren: https://github.ibm.com/functions/knative-multitenant/blob/master/docs/cloud-functions-next-gen-incubator.md
2. Knative Pywren: https://github.com/pywren/pywren-ibm-cloud/blob/master/docs/knative.md

I was able to follow the first tutorial and successfully get the example running. However, I want to use pywren as well, and I wasn't able to follow the second tutorial and think it might be a little outdated. I see it requires the users to create their own kubernetes cluster and use pywren on that cluster (I assume this might because the official knative cluster was not publicly available at the time of writing the tutorial).  However, since we already have an official kubernetes cluster for running knative (the one in the first tutorial), I am wondering if we could update the pywren tutorial to use that cluster.

In the meantime, is it possible to have a detailed hello-world-like example/tutorial?  It would be great if we could have a very detailed tutorial that shows each single step from step 0, so that everyone could simply follow to have a demo running.  Currently, a lot of details are not very obvious (e.g. to build a knative-compatible image, should we use `pywren-runtime build` as we do in regular pywren, or simply use `docker build`, or there is another specific command), so it would be great to have detailed one to follow.

**Comment by gilv** [comment]
@JosepSampe can you provide an input here? thanks
