### ISSUE TITLE
ibm_cos field is missing in obj parameter in COS map function

### ISSUE THREAD

**Issue by rmey** [pywren/pywren-ibm-cloud#225]
In previous versions of pywren-ibm-cloud it was possible to get a reference to ibm_cos variable in the map function, for example in that [notebook](https://github.com/IBM/data-pre-processing-with-pywren/blob/master/examples/facial-recognition.ipynb)  like `def preprocess_image(bucket, key, data_stream, ibm_cos):`
In the new map Function Signature for COS there is no such field in obj anymore.
```
def preprocess_image(obj):    
    
    print(obj.key)
    print(obj.data_stream.read())
    print(obj.part)
    print(obj.data_byte_range)
    print(obj.chunk_size)
    print(obj.bucket)
    
    bucket = obj.bucket
    key = obj.key
    # does not work
    # ibm_cos = obj.ibm_cos
```

**Comment by rmey** [comment]
I found in the examples that this needs to be an extra parameter and not an attribute of the obj parameter.
https://github.com/pywren/pywren-ibm-cloud/blob/master/docs/multiple-parameters.md

**Comment by gilv** [comment]
def preprocess_image(obj, ibm_cos):
