### ISSUE TITLE
Dockerfile.python37 image is broken

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#235]
./runtime/pywren_runtime build cactusone/pywren-3.7-dev:1.0.0 -f ./runtime/ibm_cf/Dockerfile.python37 

DEBUG:pywren_ibm_cloud.config:Loading configuration
DEBUG:pywren_ibm_cloud.config:Loading Compute backend module: ibm_cf
DEBUG:pywren_ibm_cloud.config:Loading Storage backend module: ibm_cos
DEBUG:pywren_ibm_cloud.compute.backends.ibm_cf.ibm_cf:Creating IBM Cloud Functions client
....

DEBUG:pywren_ibm_cloud.compute.backends.ibm_cf.ibm_cf:IBM CF client created successfully
INFO:pywren_ibm_cloud.compute.backends.ibm_cf.ibm_cf:Building a new docker image from Dockerfile
....
Sending build context to Docker daemon  8.834MB
Step 1/12 : FROM python:3.7-slim-jessie
manifest for python:3.7-slim-jessie not found: manifest unknown: manifest unknown

**Comment by JosepSampe** [comment]
@gilv Fixed, will submit in next PR
