### ISSUE TITLE
Openwhisk Pywren Credentials and Setup

### ISSUE THREAD

**Issue by shelbyt** [pywren/pywren-ibm-cloud#239]
Hi,

I'm running vanilla openwhisk locally and want to run pywren. What steps did you all use to get this to work? I saw post #62 but it did not given any details about how to do this.

For one, when I'm setting up credentials I'm not sure what to put down for region/endpoint/etc.:
![image](https://user-images.githubusercontent.com/1332316/71025571-254d8800-20bc-11ea-9d65-75fbf6eca16c.png)

When running the hello-world openwhisk, this is pretty much the only information avaiable to me:
![image](https://user-images.githubusercontent.com/1332316/71026105-567a8800-20bd-11ea-9810-85a4915f5b6f.png)

Any help getting this setup would be enormously helpful for us. Thank you for all your work on this project.

**Comment by JosepSampe** [comment]
Hi @shelbyt 
In OpenWhisk , a fully qualified name has three parts: /namespaceName/packageName/entityName. So based on the image, the **endpoint** is `http://172.31.47.60:9090` and the **namespace** is `23bc46b1-71...`. If you can access OpenWhisk without credentials, there is no need to put anything in api_key.

In any case, could you deploy the hello_world action again and verify you can invoke it by sending a curl request? `curl "http://172.31.47.60:9090/api/23bc...."`. Can you also verify you always get the same namespace when deploying actions? For example, can you share what is the output of the `wsk list` command?

**Comment by shelbyt** [comment]
>  In OpenWhisk , a fully qualified name has three parts: /namespaceName/packageName/entityName. So based on the image, the endpoint is http://172.31.47.60:9090 and the namespace is 23bc46b1-71.... If you can access OpenWhisk without credentials, there is no need to put anything in api_key.

Thank you, that was helpful. 

I can invoke by sending curl and I verify that I always get the same namespace when deploying.
See output below:

![image](https://user-images.githubusercontent.com/1332316/71039190-6e133a00-20d8-11ea-9187-0c696f25b1fb.png)



When running the testsuite `python -m pywren_ibm_cloud.tests` I seem to now be getting this error on all the tests:
![image](https://user-images.githubusercontent.com/1332316/71039332-be8a9780-20d8-11ea-9edb-2c639fdc75ad.png)

I assume this is because I have to change the [backend](https://github.com/pywren/pywren-ibm-cloud/tree/5358fbb00fd648beb48263ef9d345db7784aaddf/pywren_ibm_cloud/compute/backends) from ibm_cf to either docker or localhost?

**Comment by JosepSampe** [comment]
@shelbyt Thanks for the information. Seems the communication with the backend is slightly different between IBM CF and OpenWhisk.  Need to check other things to go ahead with this ;)

1. Can you try if you can invoke the action by using "guest" namespace?
for example: `curl http://172.31.47.60:9090/api/guest/hello`
2. Can you try if you can invoke the action by specifying api version?
for example: `curl http://172.31.47.60:9090/api/v1/guest/hello`
3. If 1 or 2 works, can you try also:
`curl http://172.31.47.60:9090/api/namespaces/guest/hello`
`curl http://172.31.47.60:9090/api/v1/namespaces/guest/hello`

**Comment by shelbyt** [comment]
Sure, to give you a full picture this is how I'm creating the API:

![image](https://user-images.githubusercontent.com/1332316/71104546-d281d800-2170-11ea-9b78-f8713a2376b7.png)

Unfortunately, none of thsoe commands you mentioned works:

![image](https://user-images.githubusercontent.com/1332316/71104665-05c46700-2171-11ea-98ac-2e97cb7b8e95.png)

**Comment by JosepSampe** [comment]
@shelbyt many thanks, In PyWren actions are not web, so can you try creating the action without `--web True`?

**Comment by shelbyt** [comment]
There is an error when doing this, I can't create an API without it being web it seems:
![image](https://user-images.githubusercontent.com/1332316/71105316-3527a380-2172-11ea-92f6-e347368029ae.png)

**Comment by JosepSampe** [comment]
I think there is no need to create the api, you can invoke the action directly

**Comment by shelbyt** [comment]
I can invoke the action, but it doesn't seem like I can curl without setting up the API parameters, is there a way to do this?

![image](https://user-images.githubusercontent.com/1332316/71107627-4e325380-2176-11ea-9a0d-0660f654252f.png)

**Comment by JosepSampe** [comment]
Can you share the output from `wsk list`?

**Comment by shelbyt** [comment]
See following:

![image](https://user-images.githubusercontent.com/1332316/71108688-77ec7a00-2178-11ea-83f4-70c2eaac2fbf.png)

**Comment by JosepSampe** [comment]
Interesting, can you try with:
```
curl http://172.31.47.60:9090/api/guest/hello
curl http://172.31.47.60:9090/api/v1/guest/hello

curl http://172.31.47.60:9090/api/_/hello
curl http://172.31.47.60:9090/api/v1/_/hello

curl http://172.31.47.60:9090/api/guest/_/hello
curl http://172.31.47.60:9090/api/v1/guest/_/hello
```

**Comment by shelbyt** [comment]
None of those seem to work:

![image](https://user-images.githubusercontent.com/1332316/71109163-871ff780-2179-11ea-9636-33caf6e6c56a.png)

**Comment by JosepSampe** [comment]
Ok, no problem, can you share the output of: `wsk action invoke /guest/hello`?

**Comment by JosepSampe** [comment]
Ok, no problem, can you share the output of: `wsk --debug action invoke /guest/hello`?

**Comment by shelbyt** [comment]
![image](https://user-images.githubusercontent.com/1332316/71109943-2bef0480-217b-11ea-8522-b0b5917130db.png)

**Comment by JosepSampe** [comment]
nice, so now you can see the full url at the beginning
```
REQUEST:
[POST] https://172...
```
So you should be able to `curl ` that url with -X POST and get the result

**Comment by JosepSampe** [comment]
This was the URL I wanted to see :)
Now, in pywren config file you have to write:
```
ibm_cf:
    endpoint: http://172.31.47.60  # https if it works with https
    namespace: guest
    api_key: should_not_work
```

In addition to the config, PyWren still requires a little change in the communication lib, I will submit a PR soon with the changes

**Comment by shelbyt** [comment]
On curl this is what happen:

![image](https://user-images.githubusercontent.com/1332316/71111695-d1f03e00-217e-11ea-8620-abdddba66ac6.png)

When I'm running this using the testing infrastructure on pywren, these are the errors:

![image](https://user-images.githubusercontent.com/1332316/71111729-dcaad300-217e-11ea-9c25-328e7033790b.png)

I think  there is something else SSL related that is causing an error but we're really close I think.

**Comment by JosepSampe** [comment]
Does curl work with http? Also, you have to delete the port 9090 from the endpoint

**Comment by shelbyt** [comment]
It doesn't work with http:
![Uploading image.png…]()

**Comment by JosepSampe** [comment]
Take a look to this: https://github.com/apache/openwhisk/blob/master/docs/rest_api.md
Seems basic auth is in `~/.wskprops` file. you can also get it by `wsk property get --auth`.
You need to write this auth in config file too. However, I have to see how this auth looks like to determine if it is the expected one by PyWren, so can you paste the output from  `wsk property get --auth`?

**Comment by shelbyt** [comment]
![image](https://user-images.githubusercontent.com/1332316/71116496-1e407b80-2189-11ea-8d83-3af0681d2d19.png)

**Comment by JosepSampe** [comment]
Yep, this one is the expected one, so copy all the key `23bc46.....wP` into api_key in config

**Comment by shelbyt** [comment]
Same SSL Error as before, but I"m glad we did figure out what the API key should be:

![image](https://user-images.githubusercontent.com/1332316/71116940-fb629700-2189-11ea-9c09-5812fd429760.png)

Error: (Note it defaults to port 443 now)

![image](https://user-images.githubusercontent.com/1332316/71116976-0fa69400-218a-11ea-8cb3-8c0b6b4fafaf.png)

**Comment by shelbyt** [comment]
See all properties below:
![image](https://user-images.githubusercontent.com/1332316/71117977-09b1b280-218c-11ea-867e-0359ecfacd83.png)

**Comment by shelbyt** [comment]
By the way I was just able to get the `hello ` program working with CURL but only after I gave it both the username/password AND passed the -k option to curl i.e. 
![image](https://user-images.githubusercontent.com/1332316/71119957-32d44200-2190-11ea-8808-39ba1047f554.png)

Result:
![image](https://user-images.githubusercontent.com/1332316/71120087-76c74700-2190-11ea-8c70-f825702f780f.png)

**Comment by JosepSampe** [comment]
This is expected. I'm modifying pywren communication lib to allow insecure OW backends

**Comment by JosepSampe** [comment]
Added fix in #245. When merged add 'insecure: True' in config file:
```
ibm_cf:
    ...
    insecure: True
```

I couldn't test it since I couldn't access to an OpenWhisk deployment, but I think the changes are enough to make it working.

**Comment by shelbyt** [comment]
Using the new commits it seems to fix the auth problem. However it was then giving me this problem:

![image](https://user-images.githubusercontent.com/1332316/71134730-3b3e7400-21b4-11ea-9a0c-22fce2ad7e30.png)

I was able to solve it by changing this in [config.py](https://github.com/pywren/pywren-ibm-cloud/blob/master/pywren_ibm_cloud/compute/backends/ibm_cf/config.py#L9)  :

![image](https://user-images.githubusercontent.com/1332316/71134750-4c878080-21b4-11ea-8477-51b9e5efd43b.png)

Then basically all the tests run! Except for one of them:
![image](https://user-images.githubusercontent.com/1332316/71135979-1ea43b00-21b8-11ea-9d18-333ba7bdbc88.png)

![image](https://user-images.githubusercontent.com/1332316/71136010-3976af80-21b8-11ea-8b97-3d4fc01e5175.png)


I believe the "timeout problem" is an OpenWhisk compatibility "issue" because the vanilla configuration in OW is to have a hard limit of 5min and pywren has 10 minutes:

https://github.com/apache/openwhisk/blob/master/docs/reference.md

> The timeout limit N is in the range [100ms..300000ms] and is set per action in milliseconds.

The same issue comes up when I try to increase the memory in pywren to 1024:
if I use that  same config.py to increase the memory I get this error:
![image](https://user-images.githubusercontent.com/1332316/71134894-c586d800-21b4-11ea-85fb-72012fea1809.png)

Once more..https://github.com/apache/openwhisk/blob/master/docs/reference.md
> The memory limit M is in the range from [128MB..512MB] and is set per action in MB.




--
And just for future people to see how awesome this is, I'm running the compute locally on OpenWhisk, but I'm using IBM COS as the storage backend:

LOCAL
![image](https://user-images.githubusercontent.com/1332316/71135055-65446600-21b5-11ea-893e-dac5fe024ba8.png)

IBM COS
![image](https://user-images.githubusercontent.com/1332316/71135030-4a71f180-21b5-11ea-8e16-de812f59cc1f.png)

Really great stuff!!!! Thanks a lot for the help! Let me know if you have any ideas about that last test that's failing, if not that's fine. You're awesome, really saved me at least a week+

**Comment by shelbyt** [comment]
Also for future reference, I was able to get 1024 mb RAM functions of openwhisk running with the openwhisk-devtools:

![image](https://user-images.githubusercontent.com/1332316/71152381-19141880-21eb-11ea-961d-ecca7783c934.png)

Just add this
`CONFIG_whisk_memory_max: 1073741824`

After these lines in the openwhisk invoker and controller:
https://github.com/apache/openwhisk-devtools/blob/master/docker-compose/docker-compose.yml#L83
https://github.com/apache/openwhisk-devtools/blob/master/docker-compose/docker-compose.yml#L126

**Comment by JosepSampe** [comment]
@shelbyt Great to know all is working fine :) Thank you alot too for your feedback. The test that fails is not an important one, so you can run function without problems.

I added a new `openwhisk_executor()` in #245 , and also a new section in configuration to easily differentiate between vanilla openwhisk clusters and IBM Cloud Functions. So you can now move your config to:
```
pywren:
    storage_bucket: ....
    compute_backend: openwhisk

openwhisk:
    endpoint: ...
    namespace: ...
    api_key: ...
    insecure: ...
```

Then, you can use pywren by instantiating a new `openwhisk_executor()`, for example:
```
import pywren_ibm_cloud as pywren

def my_function(x):
    return x + 7

if __name__ == '__main__':
    pw = pywren.openwhisk_executor()
    pw.call_async(my_function, 3)
    print(pw.get_result())
```

**Comment by shelbyt** [comment]
Got it, I'll check it out. Closing this issue!
