### ISSUE TITLE
Getting bucket name from PyWren

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#240]
I need to get bucket name which is used by PyWren internally.

Configuration always contains 

pywren: 
    storage_bucket : mybucket

Consider example

def my_func(x, ibm_cos):
    print("aha")

pw = pywren.ibm_cf_executor()
pw.map(my_func, range(1))

Is there a way to get storage_bucket inside my_func? Is there a way to get storage_bucket from pw executor?

**Comment by JosepSampe** [comment]
You can get the storage bucket from env, 
`sb = os.environ.get('PYWREN_STORAGE_BUCKET')`
In fact, you can get the whole config from environ:
`pywren_config = json.loads(os.environ.get('PYWREN_CONFIG'))`
