### ISSUE TITLE
Avoid calling exit() on the host

### ISSUE THREAD

**Issue by LachlanStuart** [pywren/pywren-ibm-cloud#243]
The current behavior when an action exits with an exception is to [exit the host process](https://github.com/pywren/pywren-ibm-cloud/blob/master/pywren_ibm_cloud/executor.py#L363)

This is undesirable because it doesn't give the calling code a chance to log, clean up, or attempt to recover (unless it specifically handles the `SystemExit` exception). 

It would be better to re-`raise` the `FunctionException` so that the caller can handle it if they choose to.

**Comment by JosepSampe** [comment]
Added fix in #245
