### ISSUE TITLE
Unable to use already built runtime

### ISSUE THREAD

**Issue by kpavel** [pywren/pywren-ibm-cloud#251]
Running `pywren-runtime create jsampe/pywren-conda:3.5` fails to create knative runtime.
Docker image tag "latest" concatenated to the end of image name when not needed.

https://github.com/pywren/pywren-ibm-cloud/blob/f42f9d4d1fe9d6b8ec1215371242192a54a2e95b/pywren_ibm_cloud/compute/backends/knative/knative.py#L239

**Comment by gilv** [comment]
@JosepSampe can you check this please?

**Comment by JosepSampe** [comment]
Added fix in #253.
However, note that the runtime `jsampe/pywren-conda:3.5` does not exist.
