### ISSUE TITLE
Error occurs when switching to `local_executor`

### ISSUE THREAD

**Issue by mbehrendt** [pywren/pywren-ibm-cloud#256]
The error message below occurs when trying to run pywren code with the `local_executor`:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pywren_ibm_cloud/storage/storage.py", line 29, in __init__
    self.storage_handler = StorageBackend(self.pywren_config[self.backend])
  File "/usr/local/lib/python3.6/dist-packages/pywren_ibm_cloud/storage/backends/ibm_cos/ibm_cos.py", line 45, in __init__
    user_agent = ibm_cos_config['user_agent']
KeyError: 'user_agent'
```

**Comment by JosepSampe** [comment]
@mbehrendt Which PyWren version are you using?

**Comment by mbehrendt** [comment]
1.4.0 @JosepSampe

**Comment by mbehrendt** [comment]
i got it resolved with a fresh install

**Comment by JosepSampe** [comment]
@mbehrendt In fact the issue exists when using a `local_executor()` with functions that contain `ibm_cos` parameter. I just added a fix in https://github.com/pywren/pywren-ibm-cloud/pull/255
