### ISSUE TITLE
map() and map_reduce() are not consistent

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#26]
Seems we need refactor both methods. So far map_reduce() contains many COS logic, while map doesn't. Since we not always need reduce but need COS related logic,  we may call map_reduce(.. reduce = None ). This is wrong. 
We need map() to support COS as well, similar to map_reduce method..

Perhaps the best would be to call map() from map_reduce() and move COS related logic to map(). This will cover all the cases

@JosepSampe need your input if this makes sense

**Comment by gilv** [comment]
@JosepSampe any input? ;)

**Comment by JosepSampe** [comment]
@gilv I'm doing some tests to see which is the best approach ;)

**Comment by JosepSampe** [comment]
@gilv Task done in #49
