### ISSUE TITLE
ParamValidationError with current master branch

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#265]
I get `ParamValidationError` when operating PyWren map over objects in COS.
if I downgrade PyWren version to 1.4.2 it works.

example PyWren DEBUG logs:
https://gist.github.com/omerb01/7b264b8287ab42ceef2e471a23744881

code is a bit complicated, please let me know if you need anything else.

**Comment by JosepSampe** [comment]
@omerb01 Based on this discussion: https://github.com/metaspace2020/pywren-annotation-pipeline/issues/55 , I decided to delete the `pickle.dumps()` located inside the `internal_storage.put_obj()` method that returns a CloudObject. Now, as with `ibm_cos.put.obj()`, the user is responsible to provide a bytes-like object when using `internal_storage.put_object()`, for eaxmple by using pickle (or any other tool),  and unpickle it when reading the CloudObject with `internal_storage.get_object()`.

So you need to change this line and pickle the data by yourself: https://github.com/metaspace2020/pywren-annotation-pipeline/blob/4afab539a71ae1fa83026cb6d270ab4a33b93fcb/annotation_pipeline/image.py#L48-L53

**Comment by omerb01** [comment]
@JosepSampe thanks :)
