### ISSUE TITLE
No such file or directory: '/home/dsxuser/.pywren_config' using Watson Studio notebook

### ISSUE THREAD

**Issue by tokamo10** [pywren/pywren-ibm-cloud#269]
I used Watson Studio notebook and executed

```
!pip install urllib3 --upgrade
!pip install pywren-ibm-cloud
import pywren_ibm_cloud as pywren

def add_seven(x):
    return x + 7

if __name__ == '__main__':
    ibmcf = pywren.ibm_cf_executor()
    ibmcf.call_async(add_seven, 3)
    print(ibmcf.get_result())
```

I got the following error:
`FileNotFoundError: [Errno 2] No such file or directory: '/home/dsxuser/.pywren_config'`

How do I run pywren using Watson Studio notebook?

**Comment by gilv** [comment]
@tokamo10 you need to define config explicitly. See this one https://github.com/pywren/pywren-ibm-cloud/blob/master/examples/hello_world.ipynb

**Comment by tokamo10** [comment]
I defined config and executed successfully.
Thank you.
