### ISSUE TITLE
issues with gevent version and inconsistency with openwhisk - to monitor

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#27]
Our Docker image is based on https://github.com/apache/incubator-openwhisk-runtime-docker/releases.  The following pull request https://github.com/apache/incubator-openwhisk-runtime-docker/pull/62 upgraded gevent and flask versions, however there is no release that contains this pull request.

For now we can't upgrade requirement.txt with recent gevent versions as it will hit version incompatibility with openwhisk. This commit https://github.com/pywren/pywren-ibm-cloud/commit/b33f7d9b54b9af697155f18dcf03578401ffee23 moved gevent to earlier release

**Comment by JosepSampe** [comment]
I think that in fact this is not an issue. Our code uses last Dockerfile and requirements from https://github.com/ibm-functions/runtime-python/tree/master/python3.6 , so they are consistent.
