### ISSUE TITLE
How to access COS from within a function?

### ISSUE THREAD

**Issue by romeokienzler** [pywren/pywren-ibm-cloud#279]
Having a look at [this](https://github.com/IBM/data-pre-processing-with-pywren/blob/master/notebooks/facial-recognition.ipynb) nb, but it is not clear to me why the signature of preprocess_image(bucket, key, data_stream, ibm_cos) differs from pw.map(preprocess_image, raw_images, remote_invocation=True) and how the reference ibm_cos is created/obtained

**Comment by gilv** [comment]
@romeokienzler PyWren invoke a function. Those are different signatures, how to invoke the function and what is the signature of the function that PyWren will automatically inject specific fields. pw.map(...) invoke.

The function has to be specific interface, for example ibm_cos is already inititated boto3 library that PyWren will inject. See this one https://github.com/pywren/pywren-ibm-cloud/blob/master/docs/data-processing.md
