### ISSUE TITLE
Trying to create 1500 action and get this error

### ISSUE THREAD

**Issue by idoyehe** [pywren/pywren-ibm-cloud#28]
{'code': '9511365e7ea98da657cca71c82673422', 'error': 'Too many concurrent requests in flight (count: 600, allowed: 600).'}

**Comment by gilv** [comment]
@JosepSampe is the retry suppose to handle this situation?

**Comment by JosepSampe** [comment]
@gilv Nop. We discussed last week this situation, in order to implement delayed retry, like 5secs frst retry, 10secs 2nd, 30secs 3rd .... But it is not solved. I added some commented code [here](https://github.com/pywren/pywren-ibm-cloud/blob/master/pywren/pywren_ibm_cloud/invokers.py) (lines 45 and 48). But we should discuss if it is enough or not.

**Comment by JosepSampe** [comment]
Added retry logic in pull request #29

**Comment by idoyehe** [comment]
It is possible to increase the allowed concurrent requests?

**Comment by gilv** [comment]
@idoyehe can you please checkout the code, rebuild and retest? Josep has implemented the retry logic, it's configurable, make sure you update your configuration file with
    #data_cleaner: <True/False>
    #invocation_retry: <True/False>
    #retry_sleeps: [1, 5, 10, 20, 30]
    #retries: 5

Default is True. You can experiment with retry_sleeps and use different seconds.
thanks

**Comment by idoyehe** [comment]
I dont get this error anymore but the all process of creating the actions and execute them becomes much slower

**Comment by gilv** [comment]
@idoyehe errors or warning prints? It is slower if we run more actions then concurrency allows.

**Comment by idoyehe** [comment]
I tried to do what @JosepSampe butit seems the process that generate each action gets stuck

**Comment by gilv** [comment]
@idoyehe if the flag set to False, then it fails because you reach maximal concurrency..

**Comment by idoyehe** [comment]
it fails from the first one....

**Comment by gilv** [comment]
@JosepSampe @idoyehe i think the issue resolved as we have retry mechanism now
