### ISSUE TITLE
how to get bucket used by pywren

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#280]
def my_func(x, ibm_cos):
  print("aha")

pw = pywren.ibm_cf_executor()
pw.map(my_func, range(1))

what is the most elegant way for my_func to get bucket name? is it passed as parameter, also when input is not from cos?
seems not documented anywhere

@JosepSampe your magic touch.

**Comment by JosepSampe** [comment]
From within a function you can access all the pywren config, and then get the bucket:
```python
def my_func(x, ibm_cos):
    pywren_config = json.loads(os.environ['PYWREN_CONFIG'])
    bucket = pywren_config['pywren']['storage_bucket']
```
