### ISSUE TITLE
not every Docker image uses requirement.txt in ibm_cf

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#281]
Some Docker images in ibm_cf doesn't use requirements.cf, for example Dockerfile.python36
Should all images we consistent?

**Comment by gilv** [comment]
@JosepSampe what is your input on this?

**Comment by JosepSampe** [comment]
Those I created yes (Dockerfile.python38 and Dockerfile.slim), the other ones, I don't know. I never used them.

This one you refer (Dockerfile.python36) can be deleted, it is the same as the Dockerfile. The only difference is the build time. With Dockerfile you have to install everything, and with Dockerfile.python36 everything is installed from `ibmfunctions/action-python-v3.6`, however it might contain different python packages versions.

**Comment by gilv** [comment]
@JosepSampe which one we need there? I actually using Dockerfile.python36 all the time :)

**Comment by JosepSampe** [comment]
If you were using `Dockerfile.python36`, you can use: https://github.com/pywren/pywren-ibm-cloud/blob/master/runtime/ibm_cf/Dockerfile
