### ISSUE TITLE
cancel PyWren restriction to upload too much iterdata

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#286]
regarding https://github.com/metaspace2020/pywren-annotation-pipeline/pull/63
I think that we shouldn't restrict PyWren's operation by any kind of input, many python modules that detect inefficiency usage - just prompt warning messages.

I suggest reducing the exception to a warning message instead, i.e changing:
```
Exception: ExecutorID 9f4e67/0 | JobID M000 - Total data exceeded maximum size of 4000000.0 bytes
```
to some kind of:
```
Warning: ExecutorID 9f4e67/0 | JobID M000 - Inefficienty of intense data usage
```
and then continue PyWren's operation as usual.

**Comment by gilv** [comment]
@omerb01 this is not Inefficienty, this is exception of maximal memory limitation :)

**Comment by omerb01** [comment]
@gilv why do we need this limitation? I assume it's because of inefficient usage
in case of Lachlan's approach in: https://github.com/metaspace2020/pywren-annotation-pipeline/pull/63
this restriction actually made him implement less efficient code

**Comment by gilv** [comment]
@omerb01 limitation of 4GB memory in Cloud Functions?

**Comment by omerb01** [comment]
@gilv I am talking about the limitation of **local** data that you provide to PyWren as an input - `iterdata` parameter for `map()` operation.

**Comment by JosepSampe** [comment]
Yes, `iterdata` is limited to 4MB for efficiency. `iterdata` is the data send from the laptop to the cloud, for this reason it is limited to this low number. 

`iterdata` should contain the minimum necessary information to spawn the functions. @omerb01 Can you explain your case and why it is better to send much more data from the client to the cloud?

**Comment by omerb01** [comment]
@JosepSampe in our case in EMBL project, we are trying to parse the whole binary dataset (could be very large) within CF, this requires passing coordinations input for each action that all together can sum up for more 40mb. the alternative is to upload these coordinations first to COS and then perform map operation on the keys - this approach is a messy workaround to do so cause it is exactly what PyWren does but manually.
it is good to mention that the coordinations, in this case, won't be much larger than 40mb.

**Comment by JosepSampe** [comment]
@omerb01 I see. Is there a chance to manage these 40MB of data directly in the cloud? I mean, are you downloading this information from a previous function execution and then upload it again to spawn the next phase? or is this information generated on the client side?

**Comment by omerb01** [comment]
@JosepSampe we do this locally, it requires a lot of changes in EMBL parser to be able to do it differently.

**Comment by JosepSampe** [comment]
I think we can put a new key in configuration to change this value, for example:
```
pywren:
    max_data_size: XX
```

What do you think?

**Comment by omerb01** [comment]
@JosepSampe why do you think it's important to enforce it at all?

**Comment by JosepSampe** [comment]
I think it is important to keep the exception because it is a clear symptom you might be doing something inefficient. Pass a huge amount of data from the client to the cloud implies 1) higher execution times (depending of the network), 2) More costs (public bandwidth is paid). 

In your case, you are an expert and you know the consequences of passing large amounts of data through `iterdata`, but most of users are not experts and don't know the consequences, trying to send huge amounts of data through `iterdata` (even GB files).

Having this limit forces users to find a more efficient way to manage the data, for example store the data into COS from within a function and send object urls instead of object data. 

In such cases where the data must be sent from the client to the cloud (yes or yes), I think the best option is to put this config parameter to increase the value. This way you have always control of the quantity of data you are sending.

**Comment by omerb01** [comment]
@JosepSampe thanks for the explanation :)
my concern about setting the config parameter is the "static approach", I can't estimate how much memory I need in this case, there could be any kind of dataset.
we know (in this case) that its size will be small enough for our purpose and also to be handled by EMBL team (for uploading).

what do you think about a parameter for `map()` that will disable the limitation - i.e. it will be configured to 40mb limitation by default and if it will be necessary to use more memory, there will be an option to disable the limit by some kind of `map(... , data_limit=False)`

**Comment by JosepSampe** [comment]
A user who sets this value in configuration is supposed to know what is he doing, so maybe simply allowing this in configuration might be enough:

```
pywren:
    data_limit: False
```

**Comment by omerb01** [comment]
@JosepSampe agreed, thanks

**Comment by JosepSampe** [comment]
Current data limis is set in bytes, maybe we can put it in in MB, or is it good for you to use bytes?

**Comment by omerb01** [comment]
@JosepSampe just for representation, I think that it will be more clear as MB

**Comment by omerb01** [comment]
@JosepSampe Tested it a bit, everything seems fine, thanks.
I have a minor suggestion, when using too much memory in the input data (iterdata) we need to wait in vain during the process of "Serializing function and data" - I suggest to detect that the data is too big and raise the exception **before** this operation.
```
2020-04-22 22:41:46,634 [INFO] pywren_ibm_cloud.config: PyWren v1.5.2-SNAPSHOT
2020-04-22 22:41:46,634 [DEBUG] pywren_ibm_cloud.config: Loading configuration
2020-04-22 22:41:46,635 [INFO] pywren_ibm_cloud.config: Getting configuration from /home/omerbelh/.pywren_config
2020-04-22 22:41:46,711 [DEBUG] pywren_ibm_cloud.config: Loading Compute backend module: ibm_cf
2020-04-22 22:41:46,735 [DEBUG] pywren_ibm_cloud.config: Loading Storage backend module: ibm_cos
2020-04-22 22:41:46,774 [DEBUG] pywren_ibm_cloud.executor: FunctionExecutor created with ID: 1dd954/0
2020-04-22 22:41:46,774 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Creating IBM COS client
2020-04-22 22:41:46,774 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Set IBM COS Endpoint to https://s3.us-east.cloud-object-storage.appdomain.cloud
2020-04-22 22:41:46,774 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Using access_key and secret_key
2020-04-22 22:41:46,799 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: IBM COS client created successfully
2020-04-22 22:41:46,799 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID 1dd954/0 - Total available workers: 256
2020-04-22 22:41:46,799 [DEBUG] pywren_ibm_cloud.compute.backends.ibm_cf.ibm_cf: Creating IBM Cloud Functions client
2020-04-22 22:41:46,799 [INFO] pywren_ibm_cloud.compute.backends.ibm_cf.ibm_cf: Set IBM CF Namespace to pywren_dev_us_east
2020-04-22 22:41:46,799 [INFO] pywren_ibm_cloud.compute.backends.ibm_cf.ibm_cf: Set IBM CF Endpoint to https://us-east.functions.cloud.ibm.com
2020-04-22 22:41:46,800 [INFO] pywren_ibm_cloud.compute.backends.ibm_cf.ibm_cf: IBM CF client created successfully
2020-04-22 22:41:46,800 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID 1dd954/0 - Creating function invoker
2020-04-22 22:41:47,073 [INFO] pywren_ibm_cloud.invoker: ExecutorID 1dd954/0 | JobID A000 - Selected Runtime: ibmfunctions/action-python-v3.6 - 256MB
2020-04-22 22:41:47,073 [DEBUG] pywren_ibm_cloud.storage.storage: Runtime metadata found in local cache
2020-04-22 22:41:47,287 [DEBUG] pywren_ibm_cloud.job.job: ExecutorID 1dd954/0 | JobID A000 - Serializing function and data
2020-04-22 22:42:58,874 [DEBUG] pywren_ibm_cloud.job.serialize: Referenced modules: {'omer.py'}
2020-04-22 22:42:58,874 [DEBUG] pywren_ibm_cloud.job.serialize: Modules to transmit: None
Traceback (most recent call last):
  File "omer.py", line 8, in <module>
    futures = pw.call_async(my_func, [iterdata])
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/executor.py", line 140, in call_async
    execution_timeout=timeout)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/job/job.py", line 49, in create_map_job
    job_created_timestamp=job_created_timestamp)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/job/job.py", line 180, in _create_job
    raise Exception(log_msg)
Exception: ExecutorID 1dd954/0 | JobID A000 - Total data exceeded maximum size of 4.0MiB
```

**Comment by JosepSampe** [comment]
I ran some tests and It is simple with one line of code to get the size of an string, it is for this reason that pywren checks the size after serializing it. For complex objects it is needed more complex logic.

The easiest way is to use `sys.getsizeof()`, can you check with your iterdata if it returns the correct size?
Alternatively we can use [Pympler](https://pympler.readthedocs.io/en/latest/), can you ckeck also your iterdata with this lib?

**Comment by omerb01** [comment]
from my experience, `sys.getsizeof()` isn't reliable cause it measures the size of the "first-level" memory layout - if you pass a list of pointers into it, it will measure only the memory needed for the pointers but not the memory that is stored inside.

I think that if we only pickle the Interdata and then doing `sys.getsizeof()`, it should be fast enough for our purpose. what do you think?

**Comment by omerb01** [comment]
Pympler claims that they measure the memory correctly:
"`pympler.asizeof` can be used to investigate how much memory certain Python objects consume. In contrast to `sys.getsizeof`, `asizeof` sizes objects recursively"

**Comment by JosepSampe** [comment]
As you said sys.getsizeof() only measures first-level memory layout. Howver within iterdata you can pass complex objects with references to other objects, so I think it would be not suitable for pywren. It is for this reason I asked you to run a test and measure the iterdata of your example to see if it returns the correct value or not.

**Comment by omerb01** [comment]
@JosepSampe Yeph, this code:
```python
import numpy as np
from pympler import asizeof
import sys

iterdata = [np.zeros(1024 ** 2)]
print(sys.getsizeof(iterdata))
print(asizeof.asized(iterdata))
```
outputs:
```
72
size 8388776, flat 72, refs[0], name '[array([0., 0., 0., ..., 0., 0., 0.])]'
```

**Comment by JosepSampe** [comment]
So, is 8388776 (~8MB) the actual size of `iterdata`? if you set `data_limit: False` in config, is the object uploaded to COS of this size?

**Comment by omerb01** [comment]
yes, I've just tested it:
![image](https://user-images.githubusercontent.com/13593227/80101595-49ddd300-857a-11ea-94c2-c1752e9c5038.png)

**Comment by JosepSampe** [comment]
Cool! So I will put pympler

**Comment by JosepSampe** [comment]
Hmm.. I tested it with another type of iteradata an it shows different size values:

```
asizeof.asizeof(iterdata): 28160 bytes
iterdata pickled size: 2500 bytes
```

So I guess in some cases pickle can reduce iterdata size

**Comment by omerb01** [comment]
@JosepSampe I'm not familiar with the compression methods of `pickle` but I know that they use compression when possible, thus `pickled_size <= original_size`.
I think we should try to pickle the iterdata and measure the given size since the data that we stored is pickled.

**Comment by JosepSampe** [comment]
"Pickle iterdata and measure the size" is what pywren is doing right now, so I think we should keep this as it is. We can't do anything else to know the actual size in advance and in an efficient way. So the user will have to wait pywren to pickle the data.
