### ISSUE TITLE
Invoker doesn't stop monitoring actions when it should

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#299]
I found that with current master branch, when I launch a bunch of invocations and then stop the main process, the other processes are still running

for example when using the following in a jupyter notebook:

first cell:
```python
import pywren_ibm_cloud as pywren

def my_func(args):
    return 'Hello World!'

pw = pywren.function_executor()
```
second cell:
```python
pw.map(my_func, range(1000))
pw.get_result()
```
when we stop the second cell, the invoker actually still run, it should be stopped by the main process.

**Comment by JosepSampe** [comment]
When are you stopping the cell? during `pw.map()` or during `pw.get_result()`. If you stop the cell during `pw.get_result()` it should stop invoker, can you verify it?

**Comment by omerb01** [comment]
yes, it seems to work. I mean for the scenario in which we stop the cell during `map()`

**Comment by JosepSampe** [comment]
Thanks @omerb01 I Will check it

**Comment by omerb01** [comment]
@JosepSampe Thanks :)
