### ISSUE TITLE
Different cobjects are created with the same key when using threads

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#302]
I think that I found a bug while trying to put a bunch of cobjects into COS using threads (instead of a for loop). I understand that there is a situation here that we need to use some kind of "lock" when we generate the relevant key.

for example, the following code:
```python
import pywren_ibm_cloud as pywren
from concurrent.futures import ThreadPoolExecutor

def my_func(args, storage):

    def put(args):
        return storage.put_cobject(b'data')

    with ThreadPoolExecutor() as pool:
        res = list(pool.map(put, range(3)))

    return res

pw = pywren.function_executor()
pw.map(my_func, range(1))
results = pw.get_result()[0]
print([c.key for c in results])
```
output:
```
['pywren.jobs/tmp/2f7e37/0/M000/00000/cloudobject_0', 'pywren.jobs/tmp/2f7e37/0/M000/00000/cloudobject_0', 'pywren.jobs/tmp/2f7e37/0/M000/00000/cloudobject_0']
```
all cobjects that were created in the process, mapped into the same key.

**Comment by JosepSampe** [comment]
I will change the cloudobject name suffix to a random id

**Comment by omerb01** [comment]
@JosepSampe Thanks, tested it and its ok
