### ISSUE TITLE
pickle may have issues with nested classes

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#31]
PyWren uses pickle to serialize and deserialize the code. If the code contains nested classes, then pickle may fail to properly deserialize the nested class and will lookup in the package level. This might produce an error  [ERROR] jobrunner: There was an exception: module '__main__' has no attribute 'XYZ'

Not sure what can be done. This issue is to document the current behavior.

**Comment by JosepSampe** [comment]
In concrete, PyWren uses [Cloudpickle ](https://github.com/cloudpipe/cloudpickle) to serialize. I saw a (more than likely) related issue: https://github.com/cloudpipe/cloudpickle/issues/53 Maybe we should open an issue directly in the Cloudpickle github.

**Comment by JosepSampe** [comment]
I finally been able to reproduce the error after moving the code of your notebook to a python file. I think it is not a pickle issue, but how a library is imported, concretely **numpy** module. 

So to avoid the issue, change:
`from numpy import exp, random`
to
`import numpy as np`

And then in the code use `np.exp` and `np.random`
