### ISSUE TITLE
Using storage APIs on the host

### ISSUE THREAD

**Issue by LachlanStuart** [pywren/pywren-ibm-cloud#320]
The `storage` interface inside functions does a great job of providing a consistent interface between storage backends, but I find the options for getting a `storage`-style API on the host confusing.

The `internal_storage` field on `FunctionExecutor` is the easiest to access, but it doesn't seem like it's intended for public use because of the "internal" name and the presence of functions like `get_job_status` and `put_runtime_meta`.

The `Storage` class can be directly constructed, but it's not directly exported from the module - you need to `from pywren_ibm_cloud.storage import Storage`, which suggests that it's also not intended to be directly accessed. Also, the constructor is slightly inconsistent with the rest of pywren - it needs `storage_backend` to be provided as an extra arg, instead of just reading it from `config` like other parts of the public API.

Are either of these options intended to be used by user code?

**Comment by LachlanStuart** [comment]
I found there are two other competing options:
* `Storage.storage_handler` / `pw.internal_storage.storage_handler` is a `*StorageBackend` instance, which is the only way to access the super-useful `list_keys` function.
* `Storage.get_client()` / `pw.internal_storage.get_client()` returns an ibm_boto3 client, but it has been modified to include 4 `cobject` methods. This is the same client supplied via the `storage` magic keyword argument in cloud functions.

I find it surprising that functions are given modified storage backend clients(ibm_boto3 for ibm_cos, a tiny custom wrapper for localhost, requests HTTP clients for ceph/infinispan/etc.), instead of `Storage`/`InternalStorage` instances, for the new `storage` magic keyword argument. Is that the long-term plan? It makes it a lot more difficult to switch between backends...

**Comment by JosepSampe** [comment]
It's true that for the `storage` magic keyword it makes more sense to return an `Stroage` instance or event the `Storage.storage_handler` (with the 4 `cobject` methods), instead of the backend client , which are different for each storage backend (ibm_boto3, requests, etc), making it more difficult to switch between backends.

From the host perspective, we can allow user to access `Storage` instance with `pw.storage`, which would be exactly the same as the magic `storage` keyword of the functions.

`InternalStorage` contains methods for managing internal data, so the idea is to avoid users to use this class.

@LachlanStuart What do you think?

**Comment by LachlanStuart** [comment]
@JosepSampe Accessing it via `pw.storage` would be very intuitive. I feel it would still be useful to also have a method to instantiate it without needing a `FunctionExecutor`. In pywren-annotation-pipeline we do some initial I/O to set up the environment before any executor is started. But, if I was only given one choice, `pw.storage` would be the most beneficial. 

I feel `Storage` is the most logical interface to expose, as it sits at a level where it can provide additional high-level functionality that isn't in the `*StorageBackend` classes. However, I would like to see the missing methods somehow accessible via `Storage`: `get_object`, `put_object`, `list_keys`, `list_objects`, `head_object`, `delete_object`, `delete_objects`. They could just be directly copied from the `storage_handler` as I don't feel they need any high-level wrapper is needed for them. It's just that having a single interface for all common operations would be better than having split high-level and low-level interfaces.

**Comment by JosepSampe** [comment]
Cool! it sounds very good. I will handle it

**Comment by LachlanStuart** [comment]
Thanks @JosepSampe !

**Comment by gilv** [comment]
@JosepSampe seems we got stuck on this one and @LachlanStuart can't progress. Can you please handle it? Thanks

**Comment by JosepSampe** [comment]
@LachlanStuart @gilv it is ready to merge and test
