### ISSUE TITLE
CloudObject key collisions

### ISSUE THREAD

**Issue by LachlanStuart** [pywren/pywren-ibm-cloud#322]
It seems like it is possible for two independently created CloudObjects to be generated with the same `key`, causing one value to overwrite the other. This can be very confusing to debug, as there is no indication that the duplication has happened, unless you manually inspect the `key` field.

This has happened to me surprisingly often. The function where I detected this happening only makes ~31 cloud objects per invocation with 256 invocations, but I've seen this happen at least 3 times in ~20 runs.

**Comment by omerb01** [comment]
I suggest to use the thread-id instead of a random suffix for each CloudObject key generation

**Comment by gilv** [comment]
@omerb01 you think random id has collisions? It's not likely to happen.. weird actually if it does

**Comment by LachlanStuart** [comment]
@gilv The random ID has only 4 hexadecimal digits. That's only `16 ** 4 == 65536` possible values.

**Comment by gilv** [comment]
@LachlanStuart wow...i missed that part. @omerb01 can you handle the fix?

**Comment by omerb01** [comment]
fix in #326 , I used a thread safe counter managed by the storage handler.
