### ISSUE TITLE
Knative installation script not found

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#331]
following the instructions to install knative for pywren: https://github.com/pywren/pywren-ibm-cloud/blob/master/docs/knative.md
the installation script link is broken.

@JosepSampe can you update the link? it is even better to commit the script into the repository ;)

**Comment by JosepSampe** [comment]
Fixed. The script was updated to install Knative 0.15.0 and istio 1.5.4. @omerb01  Yep, it is better to have the script here. I will add it ;)

**Comment by omerb01** [comment]
@JosepSampe thanks a lot :)
