### ISSUE TITLE
pywren's logging configurations control logs of all other packages

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#332]
observed an issue that prevents me from editing logging configurations as my desire before pywren executions.
I want to configure `logging` package to redirect the output logs into a file instead of stdout. I can't do that with pywren because of the lines below:

https://github.com/pywren/pywren-ibm-cloud/blob/ef18aad80254ac98eac05f4dd5d8b293f3efb8fe/pywren_ibm_cloud/config.py#L178-L200

this code overwrites every logging configurations that applied before for all packages. I think that it is a better approach to use these configurations for `pywren-ibm-cloud` package only.

**Comment by JosepSampe** [comment]
@omerb01 do you have a simple example to replicate it?

**Comment by omerb01** [comment]
@JosepSampe 
```python
import pywren_ibm_cloud as pywren
import logging

logging.basicConfig(level=logging.INFO, filename='test.log', filemode='w')

def my_func(args):
    return 'Hello World'

pw = pywren.function_executor()
pw.call_async(my_func, '')
print(pw.get_result())
```

**Comment by JosepSampe** [comment]
@omerb01 Fixed in #330

**Comment by omerb01** [comment]
@JosepSampe sorry that I didn't update it earlier, I think that the fix that you have suggested isn't what I actually meant. I think that PyWren needs a separated logger which will be imported from utils. by this approach, I can do whatever I want with the logging package. for example, I want to do a for loop that changes the basic configurations for each iteration - this won't work with your fix cause it only fixes the first time that logging configurations changes are executed.

for example:
```python
import pywren_ibm_cloud as pywren
import logging

def my_func(args):
    return 'Hello World'

pw = pywren.function_executor()

for i in range(3):
    logging.basicConfig(level=logging.INFO, filename=f'test{i}.log')
    pw.call_async(my_func, '')
    print(pw.get_result())
```
in this example, I get prints in my stdout channel although that I set "INFO" logs and directed the logs into an external file. also each iteration is redirect into different file but in practice all logs lines are appended into the same file "test0.log".

**Comment by JosepSampe** [comment]
@omerb01 Ok, will check it

**Comment by JosepSampe** [comment]
@omerb01 In fact, in the fix I added, the pywren logger is never started except you manually create an executor with the parameter `log_level`: `pywren.function_executor(log_level='INFO')`. So pywren logger will never overwrite other loggers if you don't put `log_level ` parameter in the executor.

The example above doesn't create separate log files in the same way that the next code doesn't create separate log files:

```
import logging

for i in range(3):
    logging.basicConfig(level=logging.INFO, filename=f'test{i}.log')
    logging.info(f"I'm logging {i} to file")
```

So my conclusions is that this is something related to python. Maybe there is another way to do what you want ;)

**Comment by omerb01** [comment]
I see thanks! :)
