### ISSUE TITLE
issues with map() method on COS bucket

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#48]
I have a function 

def my_map(bucket, key, data_stream, ibm_cos).

I need to run this function on every object in the bucket ( with prefix )
Tried 

input_data = 'mybucket/a/b/c'
pw = pywren.ibm_cf_executor(config=config, runtime='my run time')
pw.map(my_map, input_data)
results = pw.get_result()

DEBUG:pywren_ibm_cloud.cf_connector:Executor ID b00873ee-d75a Function 00000 - Activation ID: 6a47f9a728b645dd87f9a728b655dd6a - Time: 0.283 seconds
DEBUG:pywren_ibm_cloud.executor:Executor ID b00873ee-d75a Activation 00000 complete
DEBUG:pywren_ibm_cloud.executor:Executor ID b00873ee-d75a Invocation done: 0.387 seconds
DEBUG:pywren_ibm_cloud.wren:Executor ID b00873ee-d75a Getting results
WARNING:root:there was an error pickling. The original exception: An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist.
The pickling exception: __init__() missing 1 required positional argument: 'operation_name'

**Comment by gilv** [comment]
@JosepSampe can you help with this one please? 
This worked before when i did
pw.map_reduce(my_map,my_input, None, None ) ( one None for reduce, second None for chunk size ). But this also doesn't work anymore

**Comment by JosepSampe** [comment]
I think you need to merge Pull #45

**Comment by JosepSampe** [comment]
@gilv I commit final changes to add full consistency between map() and map_reduce(). May you need to merge Pull #49 to fix this issue.
