### ISSUE TITLE
deploy_runtime doesn't take correct versions from requirements.txt

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#54]
Current requirements.txt has ibm-cos-sdk == 2.3.3
I modified it to ibm-cos-sdk == 2.4.0 .
Executed ./deploy_runtime, however ibm-cos-sdk was not updated to 2.4.0

**Comment by JosepSampe** [comment]
`./deploy_runtime` uses an already build docker image: `ibmfunctions/action-python-v3.6`, so it doesn't take into account modifications in requirements.txt

**Comment by gilv** [comment]
@JosepSampe so how can we control cos-sdk there...or we can't for default one as it uses whatever is installed in cloud functions?

**Comment by JosepSampe** [comment]
We can't. However, it is usually updated with latest packages. In my case this image contains ibm-cos-sdk == 2.4.0
