### ISSUE TITLE
functions' args pattern

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#66]
We should consider to define a strict pattern for each external function in pywren so code like below can be understood properly:

```
def my_function(list):
    return sum(list)

pw = pywren_ibm_cloud.ibm_cf_executor()
pw.map(my_function, [[1, 2, 3], [1, 2, 3]])
result = pw.get_result()
print(result)
```

**Comment by idoyehe** [comment]
@gilv I agree with @omerb01 I tried to to it with dict and it forced me to write each key of the dict as function argument

**Comment by gilv** [comment]
@omerb01 @idoyehe 
I just tried 

     iterdata = [{1,2}, {3,4}] 
     def my_map_function(x, ibm_cos):
       res = {0}
       for i in x:
        res.add(i+7)
      return res

Works perfect. There were 2 invocations, each got a single entry which is {1,2} and {3,4}

What exactly doesn't work?

**Comment by gilv** [comment]
@idoyehe it works also with function like this 

     def my_map_function(x):
     res = {0}
     for i in x:
         res.add(i+7)
     return res

This one iterdata = [{"first": 1}, {"second": 2}]  doesn't work. Is this what you need?

**Comment by idoyehe** [comment]
no exactly,
```
iterdata = [{"first": 1 "second": 2}, {"first": 3 "second": 4}]
 def my_map_function(my_dict):
 return my_dict_parser(my_dict)
```
this generic code let me to change the "my_dict_parser" for PyWren different executors and the map function does not dependents on dict content, the keys. 

Motivation: Think that the inner function is pickled so I can change it before execution but I don't need to change my PyWren execution logic for every other inner function...

**Comment by gilv** [comment]
@idoyehe sorry, what you need? in this case iterdata = [{"first": 1 "second": 2}, {"first": 3 "second": 4}] what you expect each action to get as parameter? and how many invocatio it suppose to have based on this example?

**Comment by idoyehe** [comment]
@gilv 
 in this case iterdata = [{"first": 1 "second": 2}, {"first": 3 "second": 4}] I expect to be 2 invocations that:
in the first one my_dict = {"first": 1 "second": 2}
in the second one my_dict =  {"first": 3 "second": 4}

**Comment by JosepSampe** [comment]
There are multiple formats to send args to the functions, all are explained [here](https://github.com/pywren/pywren-ibm-cloud/blob/master/examples/multiple_parameters_map.py). Maybe it should be moved to a README ;)

@idoyehe I think that what you need is to enclose your dict into a list: 
 `[
  [{"first": 1 "second": 2}],
  [{"first": 3 "second": 4}]
 ]`

**Comment by gilv** [comment]
@idoyehe @omerb01 so based on the response from @JosepSampe it seems we simply failed to read our own example where all is perfectly explained ;) Can we close this or somethign else you need to support?

**Comment by idoyehe** [comment]
@JosepSampe @gilv Ok thanks...

**Comment by gilv** [comment]
@idoyehe so based on the input from our mighty @JosepSampe I am closing this one
