### ISSUE TITLE
deploy_runtime may choose wrong PyWren version

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#67]
local Python may contain previous PyWren releases. For example

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pywren_ibm_cloud-1.0.1-py3.6.egg:
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pywren_ibm_cloud-1.0.2-py3.6.egg:

Running ./deploy_runtime will choose the most updated version from the version.py

However running code that import PyWren 
import pywren_ibm_cloud as pywren
import os

May choose previous version and then exception happens

2019-01-01T07:26:46.115837198Z stdout: [INFO] __main__: Starting IBM Cloud Function execution
2019-01-01T07:26:46.115886537Z stdout: [INFO] wrenhandler: Starting handler
2019-01-01T07:26:46.116373172Z stdout: [ERROR] wrenhandler: There was an exception: ('WRONGVERSION', 'Pywren version mismatch', '1.0.2', '1.0.1')

In my case i simply deleted previous version fom the site-packages and issue resolved.
However this seems to be a problematic solution and we need better approach

**Comment by JosepSampe** [comment]
hmm... Which command did you use to install PyWren? I did some tests and in my case with PIP, it always overwrites previous PyWren version.

**Comment by gilv** [comment]
navigate to pywren folder and run 'python setup.py install --force'
Hpw pip works for you? pip uses repository, no?

**Comment by JosepSampe** [comment]
I think that it is not a Pywren releated bug, resd [this](https://stackoverflow.com/questions/19133831/python-how-to-force-overwriting-of-files-when-using-setup-py-install-distutil).

pip uses repository or local directory where setup.py is located. In my case I always navigate to pywren-ibm-cloud and then I use `pip install -U .` which prevents this issue.

**Comment by gilv** [comment]
@JosepSampe it is a  general Python related question, which i would like to document to prevent similar issues.  You suggest:

    cd pywren-ibm-cloud/pywren
    pip install -U .

Instead of 

    cd pywren-ibm-cloud/pywren
    python3 setup.py install --force

Is this correct?

**Comment by JosepSampe** [comment]
@gilv yes, that's right
