### ISSUE TITLE
concurrency/massive function spawning

### ISSUE THREAD

**Issue by chen116** [pywren/pywren-ibm-cloud#68]
Hi, 

I have two 2 questions about concurrency

1. 

In the paper(https://dl.acm.org/citation.cfm?id=3284029), _massive function spawning_ is mentioned and  I am wondering how to enable/configure it as a user. I looked into the source code. and I assume the parameter` invoke_pool_threads` corresponds to the _massive function spawning_  mechanism? For example, quoting from the paper : 

> For example, pretend that it is necessary to execute 1, 000 functions. In this case, the massive function spawning mechanism would internally arrange 10 groups of 100 invocations, which would be processed by 10 remote invoker functions separately.

so in that example, say the original script need to run 1000 functions, then to achieve this "10 groups of 100 invocations", user specify ` invoke_pool_threads=100` and `remote_invocation=True` ?

2. 

Generally, is concurrency enable/configure using the parameter `invoke_pool_threads` ? if not, which parameters are available? 

please let me know, thanks!

**Comment by gilv** [comment]
@chen116 This is how you can provide those parameters

    pw.map_reduce(my_map_function, iterdata, my_reduce_function,
    reducer_wait_local=False, remote_invocation=True, invoke_pool_threads=10)

**Comment by chen116** [comment]
Thanks for the reply, so am I right about the statement below?

**so in that example, say the original script need to run 1000 functions, then to achieve this "10 groups of 100 invocations", user specify `invoke_pool_threads=100` and `remote_invocation=True` ?**

Thank you very much

**Comment by gilv** [comment]
@chen116 I think so, but to be on the safe side - @JosepSampe can you confirm this? Thanks

**Comment by JosepSampe** [comment]
@chen116 Not exactly. Massive function spawning is designed to speed-up invocation phase when client is located in a high-latency (remote) network, and it is only activated with `remote invocation=True`. It uses a fixed group size of 100 invocations, not configurable for now. This fixed number comes from multiple tests with IBM Cloud functions, where 100 was the best number to do this task. 

Alternatively, you can tune `invoke_pool_threads` parameter if you don't use `remote_invocation=True`

**Comment by JosepSampe** [comment]
@chen116 Yes, it is all correct.

**Comment by gilv** [comment]
@chen116 @JosepSampe thanks. closing this one
