### ISSUE TITLE
Support cos:// for execution timeline plots

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#69]
Current code supports local directory to generate timeline plots

    pw = pywren.ibm_cf_executor()
    futures = pw.map(my_map_function, range(200))
    result pw.get_result()
    pw.create_timeline_plots(dst='/home/jsampe/desktop', name='testmap')

Map-Reduce: (need to return statuses from reduce, for now)

    pw = pywren.ibm_cf_executor()
    futures = pw.map(my_map_function, range(200), my_reduce_function)
    result = pw.get_result()
    pw.create_timeline_plots(dst='/home/jsampe/desktop', name='testmapreduce',
                         result['run_statuses'], result['invoke_statuses'] )

We need to extend this and support `cos://` as a destination folder

**Comment by idoyehe** [comment]
Nice feature, maybe you should consider add a bucket name for invocation graphs in PyWren configuration file

**Comment by gilv** [comment]
@idoyehe I guess it is enough to have `cos://<mybucket>/<path to new object>`.
The bucker already in configuration file, no need additional special bucket for this

**Comment by gilv** [comment]
@omerb01 would you like to handle it? thanks

**Comment by omerb01** [comment]
#131
