### ISSUE TITLE
tests doesn't work

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#79]
Getting "can't open data file" when try to run tests. Seems doesn't work.

    python3 test/testpywren.py init
    can't open data file
    pywren-ibm-cloud me$ ls test/
             data		testpywren.py
    pywren-ibm-cloud me$ cd test/
    test me$ python3 testpywren.py init
        can't open config file

@omerb01 Can you check this please?

**Comment by omerb01** [comment]
thanks,
fixed it on https://github.com/pywren/pywren-ibm-cloud/pull/80
