### ISSUE TITLE
Cancel invocations

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#86]
Need to understand, enable if needed, and document - how to cancel job.
I assume for remote invocation we can simply kill the action, for client side based invocations we can simple do CTRL-C...

@JosepSampe any inputs from your side  how to make it right?

**Comment by JosepSampe** [comment]
@gilv [here](https://github.com/pywren/pywren/blob/master/pywren/future.py#L76) they have implemented a way to cancel jobs by putting an object in S3. Then, `wrenhandler.py` is asking for this object each 5 seconds while the actual function code is running. Thus, when the object is there, the job is cancelled. This have the main trade-off that you may have thousands of functions asking for an object in COS each X seconds.

Now that we have CloudAMQP service, another approach could be all the `wrenhandler.py` listening to a queue. And then the client could send a message(s) to this queue to cancel all the function activations.

**Comment by gilv** [comment]
@JosepSampe thanks for explanations...yeap, we definitely doesn't want X invocations bombing object storage every 5 seconds. The queue ideas seems does the trick
