### ISSUE TITLE
chuck size map operation on several keys

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#92]
when I use `map_reduce()` method with `chunk_size` on several keys, I get a list of results that I can't know easily which of them are splited chunks and which are the whole data from a key (different keys can lead to different files in various sizes).

I think it would be better if the chunks' results of each key would return in a list, so we will get a list that includes lists which each of them refers to the relevant key and each key's result list includes the chunks' results.

current result pattern example:
```
[result_key1, result_key2_chunk1, result_key2_chunk2, result_key3]
```
suggested result pattern example:
```
[[result_key1], [result_key2_chunk1, result_key2_chunk2], [result_key3]]
```

**Comment by JosepSampe** [comment]
@omerb01 Do you refer to map()? I don't know your code, but `map_reduce()` will return just one result, right?

**Comment by omerb01** [comment]
@JosepSampe yes, I refer the output from map function after using `map_reduce()` method (actually `results` variable in reduce function is what I referred to)

**Comment by JosepSampe** [comment]
@omerb01 so, do you need to differentiate between object keys in the same reducer? because alternatively you can use `reducer_one_per_object` parameter.

**Comment by omerb01** [comment]
@JosepSampe I think there should be difference in both cases.
if I use `reducer_one_per_object` feature instead of using the same reducer, I will need to execute another reducer to treat all results together so its quite messy

**Comment by gilv** [comment]
@omerb01 why is this important to know which are splited chunks and which are the whole data from a key?

**Comment by omerb01** [comment]
@gilv it is necessary when you want to operate executions on several files, and in the end you need to process them into 1 result. In general, you have to know which element is a chunk of which file and who are the others for dedicated treats. so it would be better if you could treat each file with chunked sizes and reduce them easily into 1 result instead of getting several results of each element in iterdata (`reducer_one_per_object` feature) and then operate another reducer to get what you want.

**Comment by gilv** [comment]
@omerb01 for example, word count or AirBnb example, this is not relevant, right? We just process chunk or file the same way

**Comment by omerb01** [comment]
@gilv I don't familiar with AirBnb example but in word count examples, if you process several files from cos in chunks, you won't know which file is a chunk and what file its belong to in the reducer - so you may split the file wrongly in a middle of a word and count 2 subwords instead of 1.

**Comment by JosepSampe** [comment]
@omerb01  In the word count case, If the dataset is row-based, i.e., the dataset contains lines ended with "\n" (for example a common book), this case you mentioned will never happen with the new partitioner. If the dataset is a "bag of words", i.e., one after another without new lines ("\n"), it can happen. However we can adapt partitioner to avoid this issue.

**Comment by omerb01** [comment]
@JosepSampe 
thanks for making it clear for the example.
maybe it will be better to set this by generic configurations so partitioner could split files by `chunk_size` and also will avoid cutting lines before special characters which the user provided them.
avoiding partitioner for cutting words before ' ' char (in case of "bag of words" example) will solve this case but probably don't all cases, so as I suggested before, difference between keys' chunks will also help.

**Comment by omerb01** [comment]
since we got `obj.part` we can close this thread
