### ISSUE TITLE
Deploy Python 3.7 action

### ISSUE THREAD

**Issue by idoyehe** [pywren/pywren-ibm-cloud#97]
it seems that IBM cloud function already support python 3.7. you can review the it here:  [IBM Cloud Blog](https://www.ibm.com/blogs/bluemix/2019/02/ibm-cloud-functions-improves-performance-for-python-3-7-actions/)

The blog claim it is faster than python 3.6, it will be grate if the default runtime will be python 3.7

**Comment by gilv** [comment]
@idoyehe thanks for reporting this...let me explore in more details and we decide on the next step. I put this on hold for now, as more need to be investigated

**Comment by JosepSampe** [comment]
@gilv @idoyehe With pull #112 , Python3.7 becomes default runtime in PyWren (With this pull request, Python 3.5, 3.6 and 3.7 have default runtime). Now PyWren internally checks the Python version and deploys the appropriate runtime, totally transparent to the users.

I did some tests, and seems that the Python 3.7 runtime is better in the invocation phase than the Python 3.6 one:
Python 3.6 runtime:
![rabbitmq36_timeline](https://user-images.githubusercontent.com/10448186/55555596-eb7f5180-56e5-11e9-8af3-a15579c4ee63.png)

Python 3.7 runtime:
![rabbitmq37_timeline](https://user-images.githubusercontent.com/10448186/55555607-f33ef600-56e5-11e9-8428-04c254c4ddd6.png)

**Comment by gilv** [comment]
Looks like we can close it..
